<!--# (PART\*) Data Structures {-}-->

# **DATA STRUCTURES**  {#second-section -}

In this section, the main types of objects used in R will be introduced. Specifically, the main structures in which data can be organized: Vectors, Matrices, Data Frames, and Lists.

For each of them, we will describe their characteristics and see how to create, modify, and manipulate them as needed.

The chapters are organized as follows:

- **Chapter \@ref(vector) - Vectors**. We will learn the characteristics and use of vectors, also focusing on the different data types.
- **Chapter \@ref(factor) - Factors**. We will learn the characteristics and use of factors, which are a specific type of vector used for categorical and ordinal variables.
- **Chapter \@ref(matrix) - Matrices**. We will learn the characteristics and use of matrices, also introducing arrays.
- **Chapter \@ref(dataframe) - Data Frames**. We will learn the characteristics and use of data frames, the most commonly used object in data analysis.
- **Chapter \@ref(list) - Lists**. We will learn the characteristics and use of lists.
