<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter "10 Dataframe | Introduction to R</title>
  <meta name="description" content="This is an introductory book on R produced by Psicostat, an interdisciplinary research group that combines a passion for statistics and psychology." />
  <meta name="generator" content="bookdown 0.37 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter "10 Dataframe | Introduction to R" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="https://psicostat.github.io/Introduction2R_EN/images/logo_psicostat.png" />
  <meta property="og:description" content="This is an introductory book on R produced by Psicostat, an interdisciplinary research group that combines a passion for statistics and psychology." />
  <meta name="github-repo" content="psicostat/Introduction2R_EN" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter "10 Dataframe | Introduction to R" />
  
  <meta name="twitter:description" content="This is an introductory book on R produced by Psicostat, an interdisciplinary research group that combines a passion for statistics and psychology." />
  <meta name="twitter:image" content="https://psicostat.github.io/Introduction2R_EN/images/logo_psicostat.png" />

<meta name="author" content="Claudio Zandonella Callegher and Filippo Gambarota (revision and translation into English by Enrico Toffalini), members of Psicostat" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="matrix.html"/>
<link rel="next" href="list.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Presentation</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#why-r"><i class="fa fa-check"></i>Why R</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#contents"><i class="fa fa-check"></i>Contents</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#resources"><i class="fa fa-check"></i>Resources</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#psicostat"><i class="fa fa-check"></i>Psicostat</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#contribute"><i class="fa fa-check"></i>Contribute</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i>Acknowledgements</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#license"><i class="fa fa-check"></i>License</a></li>
</ul></li>
<li class="part"><span><b>Get Started</b></span></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="1" data-path="install.html"><a href="install.html"><i class="fa fa-check"></i><b>1</b> Installing R e RStudio</a>
<ul>
<li class="chapter" data-level="1.1" data-path="install.html"><a href="install.html#install-r"><i class="fa fa-check"></i><b>1.1</b> Installing R</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="install.html"><a href="install.html#r-windows"><i class="fa fa-check"></i><b>1.1.1</b> R Windows</a></li>
<li class="chapter" data-level="1.1.2" data-path="install.html"><a href="install.html#r-macos"><i class="fa fa-check"></i><b>1.1.2</b> R MacOS</a></li>
<li class="chapter" data-level="1.1.3" data-path="install.html"><a href="install.html#r-linux"><i class="fa fa-check"></i><b>1.1.3</b> R Linux</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="install.html"><a href="install.html#installing-r-studio"><i class="fa fa-check"></i><b>1.2</b> Installing R Studio</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="install.html"><a href="install.html#r-studio-on-linux"><i class="fa fa-check"></i><b>1.2.1</b> R Studio on Linux</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="rstudio-gui.html"><a href="rstudio-gui.html"><i class="fa fa-check"></i><b>2</b> RStudio Interface</a></li>
<li class="chapter" data-level="3" data-path="first-commands.html"><a href="first-commands.html"><i class="fa fa-check"></i><b>3</b> First steps in R</a>
<ul>
<li class="chapter" data-level="3.1" data-path="first-commands.html"><a href="first-commands.html#math-operators"><i class="fa fa-check"></i><b>3.1</b> Mathematical Operators</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="first-commands.html"><a href="first-commands.html#order-of-operations"><i class="fa fa-check"></i><b>3.1.1</b> Order of Operations</a></li>
<li class="chapter" data-level="" data-path="first-commands.html"><a href="first-commands.html#exercises"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="first-commands.html"><a href="first-commands.html#operators-rel-log"><i class="fa fa-check"></i><b>3.2</b> Relational and Logical Operators</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="first-commands.html"><a href="first-commands.html#relational-operators"><i class="fa fa-check"></i><b>3.2.1</b> Relational Operators</a></li>
<li class="chapter" data-level="3.2.2" data-path="first-commands.html"><a href="first-commands.html#logical-operators"><i class="fa fa-check"></i><b>3.2.2</b> Logical Operators</a></li>
<li class="chapter" data-level="3.2.3" data-path="first-commands.html"><a href="first-commands.html#order-of-evaluation-of-relations"><i class="fa fa-check"></i><b>3.2.3</b> Order of Evaluation of Relations</a></li>
<li class="chapter" data-level="" data-path="first-commands.html"><a href="first-commands.html#exercises-1"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="objects-functions.html"><a href="objects-functions.html"><i class="fa fa-check"></i><b>4</b> Two Inseparable Companions</a>
<ul>
<li class="chapter" data-level="4.1" data-path="objects-functions.html"><a href="objects-functions.html#objects-section"><i class="fa fa-check"></i><b>4.1</b> Objects</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="objects-functions.html"><a href="objects-functions.html#assign"><i class="fa fa-check"></i><b>4.1.1</b> Assigning and Calling an Object</a></li>
<li class="chapter" data-level="4.1.2" data-path="objects-functions.html"><a href="objects-functions.html#objects-names"><i class="fa fa-check"></i><b>4.1.2</b> Object Names</a></li>
<li class="chapter" data-level="4.1.3" data-path="objects-functions.html"><a href="objects-functions.html#data-types-and-data-structures"><i class="fa fa-check"></i><b>4.1.3</b> Data Types and Data Structures</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="objects-functions.html"><a href="objects-functions.html#functions-def"><i class="fa fa-check"></i><b>4.2</b> Functions</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="objects-functions.html"><a href="objects-functions.html#function-arguments"><i class="fa fa-check"></i><b>4.2.1</b> Function Arguments</a></li>
<li class="chapter" data-level="4.2.2" data-path="objects-functions.html"><a href="objects-functions.html#help"><i class="fa fa-check"></i><b>4.2.2</b> Help! I need Somebody…Help!</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="working-environment.html"><a href="working-environment.html"><i class="fa fa-check"></i><b>5</b> Working Environment</a>
<ul>
<li class="chapter" data-level="5.1" data-path="working-environment.html"><a href="working-environment.html#environment"><i class="fa fa-check"></i><b>5.1</b> Environment</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="working-environment.html"><a href="working-environment.html#adding-objects-to-the-environment"><i class="fa fa-check"></i><b>5.1.1</b> Adding Objects to the Environment</a></li>
<li class="chapter" data-level="5.1.2" data-path="working-environment.html"><a href="working-environment.html#removing-objects-from-the-environment"><i class="fa fa-check"></i><b>5.1.2</b> Removing Objects from the Environment</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="working-environment.html"><a href="working-environment.html#working-directory"><i class="fa fa-check"></i><b>5.2</b> Working Directory</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="working-environment.html"><a href="working-environment.html#computer-organization"><i class="fa fa-check"></i><b>5.2.1</b> Computer Organization</a></li>
<li class="chapter" data-level="5.2.2" data-path="working-environment.html"><a href="working-environment.html#absolute-path-and-relative-path"><i class="fa fa-check"></i><b>5.2.2</b> Absolute Path and Relative Path</a></li>
<li class="chapter" data-level="5.2.3" data-path="working-environment.html"><a href="working-environment.html#working-directory-in-r"><i class="fa fa-check"></i><b>5.2.3</b> Working Directory in R</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="working-environment.html"><a href="working-environment.html#packages"><i class="fa fa-check"></i><b>5.3</b> R-packages</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="working-environment.html"><a href="working-environment.html#install.packages"><i class="fa fa-check"></i><b>5.3.1</b> install.packages()</a></li>
<li class="chapter" data-level="5.3.2" data-path="working-environment.html"><a href="working-environment.html#library"><i class="fa fa-check"></i><b>5.3.2</b> library()</a></li>
<li class="chapter" data-level="5.3.3" data-path="working-environment.html"><a href="working-environment.html#updating-and-removing-packages"><i class="fa fa-check"></i><b>5.3.3</b> Updating and Removing Packages</a></li>
<li class="chapter" data-level="5.3.4" data-path="working-environment.html"><a href="working-environment.html#package-documentation"><i class="fa fa-check"></i><b>5.3.4</b> Package Documentation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="working-session.html"><a href="working-session.html"><i class="fa fa-check"></i><b>6</b> Working Session</a>
<ul>
<li class="chapter" data-level="6.1" data-path="working-session.html"><a href="working-session.html#organizing-scripts"><i class="fa fa-check"></i><b>6.1</b> Organizing Scripts</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="working-session.html"><a href="working-session.html#creating-sections"><i class="fa fa-check"></i><b>6.1.1</b> Creating Sections</a></li>
<li class="chapter" data-level="6.1.2" data-path="working-session.html"><a href="working-session.html#sintax"><i class="fa fa-check"></i><b>6.1.2</b> Syntax</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="working-session.html"><a href="working-session.html#organizing-projects"><i class="fa fa-check"></i><b>6.2</b> Organizing Projects</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="working-session.html"><a href="working-session.html#rstudio-projects"><i class="fa fa-check"></i><b>6.2.1</b> RStudio Projects</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="working-session.html"><a href="working-session.html#messages-warnings-e-errors"><i class="fa fa-check"></i><b>6.3</b> Messages, Warnings e Errors</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="working-session.html"><a href="working-session.html#resolving-errors"><i class="fa fa-check"></i><b>6.3.1</b> Resolving Errors</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>Data Structures</b></span></li>
<li class="chapter" data-level="" data-path="second-section.html"><a href="second-section.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="7" data-path="vector.html"><a href="vector.html"><i class="fa fa-check"></i><b>7</b> Vectors</a>
<ul>
<li class="chapter" data-level="7.1" data-path="vector.html"><a href="vector.html#creation"><i class="fa fa-check"></i><b>7.1</b> Creation</a>
<ul>
<li class="chapter" data-level="" data-path="vector.html"><a href="vector.html#exercises-2"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="vector.html"><a href="vector.html#vector-selection"><i class="fa fa-check"></i><b>7.2</b> Selecting Elements</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="vector.html"><a href="vector.html#vector-selection-advanced"><i class="fa fa-check"></i><b>7.2.1</b> Advanced Uses of Selection</a></li>
<li class="chapter" data-level="" data-path="vector.html"><a href="vector.html#exercises-3"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="vector.html"><a href="vector.html#vector-functions"><i class="fa fa-check"></i><b>7.3</b> Functions and Operations</a>
<ul>
<li class="chapter" data-level="" data-path="vector.html"><a href="vector.html#exercises-4"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="vector.html"><a href="vector.html#data-type"><i class="fa fa-check"></i><b>7.4</b> Data Type</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="vector.html"><a href="vector.html#character"><i class="fa fa-check"></i><b>7.4.1</b> Character</a></li>
<li class="chapter" data-level="7.4.2" data-path="vector.html"><a href="vector.html#numeric"><i class="fa fa-check"></i><b>7.4.2</b> Numeric</a></li>
<li class="chapter" data-level="7.4.3" data-path="vector.html"><a href="vector.html#integer"><i class="fa fa-check"></i><b>7.4.3</b> Integer</a></li>
<li class="chapter" data-level="7.4.4" data-path="vector.html"><a href="vector.html#logical-vector"><i class="fa fa-check"></i><b>7.4.4</b> Logical</a></li>
<li class="chapter" data-level="7.4.5" data-path="vector.html"><a href="vector.html#special-values"><i class="fa fa-check"></i><b>7.4.5</b> Special Values</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="factor.html"><a href="factor.html"><i class="fa fa-check"></i><b>8</b> Factors</a>
<ul>
<li class="chapter" data-level="8.1" data-path="factor.html"><a href="factor.html#attributes"><i class="fa fa-check"></i><b>8.1</b> Object Attributes</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="factor.html"><a href="factor.html#attributes-of-a-vector"><i class="fa fa-check"></i><b>8.1.1</b> Attributes of a Vector</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="factor.html"><a href="factor.html#factors"><i class="fa fa-check"></i><b>8.2</b> Factors</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="factor.html"><a href="factor.html#factor-structure"><i class="fa fa-check"></i><b>8.2.1</b> Factor Structure</a></li>
<li class="chapter" data-level="8.2.2" data-path="factor.html"><a href="factor.html#factor-operations"><i class="fa fa-check"></i><b>8.2.2</b> Factor Operations</a></li>
<li class="chapter" data-level="8.2.3" data-path="factor.html"><a href="factor.html#ordinal-factors"><i class="fa fa-check"></i><b>8.2.3</b> Ordinal Factors</a></li>
<li class="chapter" data-level="" data-path="factor.html"><a href="factor.html#exercises-5"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="matrix.html"><a href="matrix.html"><i class="fa fa-check"></i><b>9</b> Matrices</a>
<ul>
<li class="chapter" data-level="9.1" data-path="matrix.html"><a href="matrix.html#creation-1"><i class="fa fa-check"></i><b>9.1</b> Creation</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="matrix.html"><a href="matrix.html#matrix-types"><i class="fa fa-check"></i><b>9.1.1</b> Matrix types</a></li>
<li class="chapter" data-level="" data-path="matrix.html"><a href="matrix.html#exercises-6"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="matrix.html"><a href="matrix.html#sel-matrix"><i class="fa fa-check"></i><b>9.2</b> Element Selection</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="matrix.html"><a href="matrix.html#matrix-selection-advanced"><i class="fa fa-check"></i><b>9.2.1</b> Advanced Selection Uses</a></li>
<li class="chapter" data-level="" data-path="matrix.html"><a href="matrix.html#exercises-7"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="matrix.html"><a href="matrix.html#functions-and-operations"><i class="fa fa-check"></i><b>9.3</b> Functions and Operations</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="matrix.html"><a href="matrix.html#mat-prop"><i class="fa fa-check"></i><b>9.3.1</b> Attributes of a Matrix</a></li>
<li class="chapter" data-level="9.3.2" data-path="matrix.html"><a href="matrix.html#matrix-bind"><i class="fa fa-check"></i><b>9.3.2</b> Combining Matrices</a></li>
<li class="chapter" data-level="9.3.3" data-path="matrix.html"><a href="matrix.html#mathematical-operators"><i class="fa fa-check"></i><b>9.3.3</b> Mathematical Operators</a></li>
<li class="chapter" data-level="" data-path="matrix.html"><a href="matrix.html#exercises-8"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="matrix.html"><a href="matrix.html#arrays"><i class="fa fa-check"></i><b>9.4</b> Arrays</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="dataframe.html"><a href="dataframe.html"><i class="fa fa-check"></i><b>10</b> Dataframe</a>
<ul>
<li class="chapter" data-level="10.1" data-path="dataframe.html"><a href="dataframe.html#creating-a-dataframe"><i class="fa fa-check"></i><b>10.1</b> Creating a dataframe</a>
<ul>
<li class="chapter" data-level="" data-path="dataframe.html"><a href="dataframe.html#exercises-9"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="dataframe.html"><a href="dataframe.html#sel-df"><i class="fa fa-check"></i><b>10.2</b> Selecting Elements</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="dataframe.html"><a href="dataframe.html#advanced-selection-uses"><i class="fa fa-check"></i><b>10.2.1</b> Advanced Selection Uses</a></li>
<li class="chapter" data-level="" data-path="dataframe.html"><a href="dataframe.html#exercises-10"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="dataframe.html"><a href="dataframe.html#functions-and-operations-1"><i class="fa fa-check"></i><b>10.3</b> Functions and Operations</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="dataframe.html"><a href="dataframe.html#attributes-of-a-dataframe"><i class="fa fa-check"></i><b>10.3.1</b> Attributes of a Dataframe</a></li>
<li class="chapter" data-level="10.3.2" data-path="dataframe.html"><a href="dataframe.html#merging-dataframes"><i class="fa fa-check"></i><b>10.3.2</b> Merging Dataframes</a></li>
<li class="chapter" data-level="10.3.3" data-path="dataframe.html"><a href="dataframe.html#dataframe-information"><i class="fa fa-check"></i><b>10.3.3</b> Dataframe Information</a></li>
<li class="chapter" data-level="" data-path="dataframe.html"><a href="dataframe.html#exercises-11"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="list.html"><a href="list.html"><i class="fa fa-check"></i><b>11</b> Lists</a>
<ul>
<li class="chapter" data-level="11.1" data-path="list.html"><a href="list.html#creating-lists"><i class="fa fa-check"></i><b>11.1</b> Creating Lists</a>
<ul>
<li class="chapter" data-level="" data-path="list.html"><a href="list.html#exercises-12"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="list.html"><a href="list.html#selecting-elements"><i class="fa fa-check"></i><b>11.2</b> Selecting Elements</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="list.html"><a href="list.html#advanced-selection-uses-1"><i class="fa fa-check"></i><b>11.2.1</b> Advanced Selection Uses</a></li>
<li class="chapter" data-level="" data-path="list.html"><a href="list.html#exercises-13"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="list.html"><a href="list.html#functions-and-operations-2"><i class="fa fa-check"></i><b>11.3</b> Functions and Operations</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="list.html"><a href="list.html#attributes-of-a-list"><i class="fa fa-check"></i><b>11.3.1</b> Attributes of a List</a></li>
<li class="chapter" data-level="11.3.2" data-path="list.html"><a href="list.html#merging-lists"><i class="fa fa-check"></i><b>11.3.2</b> Merging Lists</a></li>
<li class="chapter" data-level="11.3.3" data-path="list.html"><a href="list.html#list-information"><i class="fa fa-check"></i><b>11.3.3</b> List Information</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="list.html"><a href="list.html#nested-structure"><i class="fa fa-check"></i><b>11.4</b> Nested Structure</a></li>
</ul></li>
<li class="part"><span><b>Algorithms</b></span></li>
<li class="chapter" data-level="" data-path="third-section.html"><a href="third-section.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="12" data-path="functions.html"><a href="functions.html"><i class="fa fa-check"></i><b>12</b> Definition of Functions</a>
<ul>
<li class="chapter" data-level="12.1" data-path="functions.html"><a href="functions.html#creating-a-function"><i class="fa fa-check"></i><b>12.1</b> Creating a Function</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="functions.html"><a href="functions.html#defining-inputs-and-outputs"><i class="fa fa-check"></i><b>12.1.1</b> Defining Inputs and Outputs</a></li>
<li class="chapter" data-level="" data-path="functions.html"><a href="functions.html#exercises-14"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="functions.html"><a href="functions.html#working-with-functions"><i class="fa fa-check"></i><b>12.2</b> Working with Functions</a></li>
<li class="chapter" data-level="12.3" data-path="functions.html"><a href="functions.html#function-environment"><i class="fa fa-check"></i><b>12.3</b> Function Environment</a></li>
<li class="chapter" data-level="12.4" data-path="functions.html"><a href="functions.html#best-practices"><i class="fa fa-check"></i><b>12.4</b> Best Practices</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="functions.html"><a href="functions.html#when-is-a-function-necessary"><i class="fa fa-check"></i><b>12.4.1</b> When is a Function Necessary?</a></li>
<li class="chapter" data-level="12.4.2" data-path="functions.html"><a href="functions.html#choosing-the-name-of-a-function"><i class="fa fa-check"></i><b>12.4.2</b> Choosing the Name of a Function</a></li>
<li class="chapter" data-level="12.4.3" data-path="functions.html"><a href="functions.html#simplifying-the-number-of-operations-and-outputs"><i class="fa fa-check"></i><b>12.4.3</b> Simplifying the Number of Operations and Outputs</a></li>
<li class="chapter" data-level="12.4.4" data-path="functions.html"><a href="functions.html#commenting-and-documenting"><i class="fa fa-check"></i><b>12.4.4</b> Commenting and Documenting</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="functions.html"><a href="functions.html#importing-a-function"><i class="fa fa-check"></i><b>12.5</b> Importing a Function</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="conditionals.html"><a href="conditionals.html"><i class="fa fa-check"></i><b>13</b> Conditional Programming</a>
<ul>
<li class="chapter" data-level="13.1" data-path="conditionals.html"><a href="conditionals.html#conditional-structures"><i class="fa fa-check"></i><b>13.1</b> Conditional Structures</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="conditionals.html"><a href="conditionals.html#if"><i class="fa fa-check"></i><b>13.1.1</b> if</a></li>
<li class="chapter" data-level="13.1.2" data-path="conditionals.html"><a href="conditionals.html#ifelse"><i class="fa fa-check"></i><b>13.1.2</b> if…else</a></li>
<li class="chapter" data-level="13.1.3" data-path="conditionals.html"><a href="conditionals.html#nested"><i class="fa fa-check"></i><b>13.1.3</b> Nested</a></li>
<li class="chapter" data-level="" data-path="conditionals.html"><a href="conditionals.html#exercises-15"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="conditionals.html"><a href="conditionals.html#other-conditional-operators"><i class="fa fa-check"></i><b>13.2</b> Other Conditional Operators</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="conditionals.html"><a href="conditionals.html#switch"><i class="fa fa-check"></i><b>13.2.1</b> switch</a></li>
<li class="chapter" data-level="13.2.2" data-path="conditionals.html"><a href="conditionals.html#ifelse-1"><i class="fa fa-check"></i><b>13.2.2</b> ifelse</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="loop.html"><a href="loop.html"><i class="fa fa-check"></i><b>14</b> Iterative Programming</a>
<ul>
<li class="chapter" data-level="14.1" data-path="loop.html"><a href="loop.html#loops"><i class="fa fa-check"></i><b>14.1</b> Loops</a>
<ul>
<li class="chapter" data-level="14.1.1" data-path="loop.html"><a href="loop.html#for"><i class="fa fa-check"></i><b>14.1.1</b> For</a></li>
<li class="chapter" data-level="14.1.2" data-path="loop.html"><a href="loop.html#while"><i class="fa fa-check"></i><b>14.1.2</b> While</a></li>
<li class="chapter" data-level="14.1.3" data-path="loop.html"><a href="loop.html#next-and-break"><i class="fa fa-check"></i><b>14.1.3</b> Next and Break</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="loop.html"><a href="loop.html#nested-loops"><i class="fa fa-check"></i><b>14.2</b> Nested Loops</a>
<ul>
<li class="chapter" data-level="" data-path="loop.html"><a href="loop.html#exercises-16"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="loop.html"><a href="loop.html#apply-family"><i class="fa fa-check"></i><b>14.3</b> Apply Family</a>
<ul>
<li class="chapter" data-level="14.3.1" data-path="loop.html"><a href="loop.html#which-functions-to-apply"><i class="fa fa-check"></i><b>14.3.1</b> Which Functions to Apply?</a></li>
<li class="chapter" data-level="14.3.2" data-path="loop.html"><a href="loop.html#apply"><i class="fa fa-check"></i><b>14.3.2</b> apply</a></li>
<li class="chapter" data-level="14.3.3" data-path="loop.html"><a href="loop.html#tapply"><i class="fa fa-check"></i><b>14.3.3</b> tapply</a></li>
<li class="chapter" data-level="14.3.4" data-path="loop.html"><a href="loop.html#lapply"><i class="fa fa-check"></i><b>14.3.4</b> lapply</a></li>
<li class="chapter" data-level="14.3.5" data-path="loop.html"><a href="loop.html#sapply"><i class="fa fa-check"></i><b>14.3.5</b> sapply</a></li>
<li class="chapter" data-level="14.3.6" data-path="loop.html"><a href="loop.html#vapply"><i class="fa fa-check"></i><b>14.3.6</b> vapply</a></li>
<li class="chapter" data-level="14.3.7" data-path="loop.html"><a href="loop.html#list-of-functions-applied-to-a-list-of-objects"><i class="fa fa-check"></i><b>14.3.7</b> List of Functions Applied to a List of Objects</a></li>
<li class="chapter" data-level="14.3.8" data-path="loop.html"><a href="loop.html#mapply"><i class="fa fa-check"></i><b>14.3.8</b> mapply</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="loop.html"><a href="loop.html#replicate"><i class="fa fa-check"></i><b>14.4</b> Replicate</a></li>
</ul></li>
<li class="part"><span><b>Case study</b></span></li>
<li class="chapter" data-level="" data-path="introduction-1.html"><a href="introduction-1.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="15" data-path="attachment.html"><a href="attachment.html"><i class="fa fa-check"></i><b>15</b> Caso Studio I: Attachment</a>
<ul>
<li class="chapter" data-level="15.1" data-path="attachment.html"><a href="attachment.html#infobox"><i class="fa fa-check"></i><b>15.1</b> Infobox</a></li>
</ul></li>
<li class="part"><span><b>Advanced Topics</b></span></li>
<li class="chapter" data-level="" data-path="fourth-section.html"><a href="fourth-section.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="16" data-path="strings.html"><a href="strings.html"><i class="fa fa-check"></i><b>16</b> Strings</a>
<ul>
<li class="chapter" data-level="16.1" data-path="strings.html"><a href="strings.html#comparing-strings"><i class="fa fa-check"></i><b>16.1</b> Comparing Strings</a></li>
<li class="chapter" data-level="16.2" data-path="strings.html"><a href="strings.html#constructing-strings"><i class="fa fa-check"></i><b>16.2</b> Constructing Strings</a>
<ul>
<li class="chapter" data-level="16.2.1" data-path="strings.html"><a href="strings.html#tolower-and-toupper"><i class="fa fa-check"></i><b>16.2.1</b> <code>tolower()</code> and <code>toupper()</code></a></li>
<li class="chapter" data-level="16.2.2" data-path="strings.html"><a href="strings.html#paste-and-paste0"><i class="fa fa-check"></i><b>16.2.2</b> <code>paste()</code> and <code>paste0()</code></a></li>
<li class="chapter" data-level="16.2.3" data-path="strings.html"><a href="strings.html#sprinf"><i class="fa fa-check"></i><b>16.2.3</b> <code>sprinf()</code></a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="strings.html"><a href="strings.html#indexing-strings"><i class="fa fa-check"></i><b>16.3</b> Indexing Strings</a>
<ul>
<li class="chapter" data-level="16.3.1" data-path="strings.html"><a href="strings.html#nchar"><i class="fa fa-check"></i><b>16.3.1</b> <code>nchar()</code></a></li>
<li class="chapter" data-level="16.3.2" data-path="strings.html"><a href="strings.html#gregexpr-and-regexpr"><i class="fa fa-check"></i><b>16.3.2</b> <code>gregexpr()</code> and <code>regexpr()</code></a></li>
<li class="chapter" data-level="16.3.3" data-path="strings.html"><a href="strings.html#substr-and-substring"><i class="fa fa-check"></i><b>16.3.3</b> <code>substr()</code> and <code>substring()</code></a></li>
<li class="chapter" data-level="16.3.4" data-path="strings.html"><a href="strings.html#startwith-and-endswith"><i class="fa fa-check"></i><b>16.3.4</b> <code>startWith()</code> and <code>endsWith()</code></a></li>
<li class="chapter" data-level="16.3.5" data-path="strings.html"><a href="strings.html#grep-and-grepl"><i class="fa fa-check"></i><b>16.3.5</b> <code>grep()</code> and <code>grepl()</code></a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="strings.html"><a href="strings.html#manipulating-strings"><i class="fa fa-check"></i><b>16.4</b> Manipulating Strings</a>
<ul>
<li class="chapter" data-level="16.4.1" data-path="strings.html"><a href="strings.html#gsub-and-sub"><i class="fa fa-check"></i><b>16.4.1</b> <code>gsub()</code> and <code>sub()</code></a></li>
<li class="chapter" data-level="16.4.2" data-path="strings.html"><a href="strings.html#strsplit"><i class="fa fa-check"></i><b>16.4.2</b> <code>strsplit()</code></a></li>
</ul></li>
<li class="chapter" data-level="16.5" data-path="strings.html"><a href="strings.html#regular-expression-regex"><i class="fa fa-check"></i><b>16.5</b> Regular Expression (REGEX)</a></li>
<li class="chapter" data-level="16.6" data-path="strings.html"><a href="strings.html#further-reading"><i class="fa fa-check"></i><b>16.6</b> Further Reading</a>
<ul>
<li class="chapter" data-level="16.6.1" data-path="strings.html"><a href="strings.html#useful-resources"><i class="fa fa-check"></i><b>16.6.1</b> Useful Resources</a></li>
<li class="chapter" data-level="16.6.2" data-path="strings.html"><a href="strings.html#other-useful-functions"><i class="fa fa-check"></i><b>16.6.2</b> Other Useful Functions</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"><span style="font-size: 2.5em">Introduction to R</span></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="dataframe" class="section level1 hasAnchor" number="10">
<h1><span class="header-section-number">Chapter "10</span> Dataframe<a href="dataframe.html#dataframe" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>I <code>dataframe</code> sono uno degli oggetti più utilizzati in R per rappresentare i propri dati. In modo analogo alle matrici, i <code>dataframe</code> sono una struttura <strong>bidimensionale</strong> dove i dati sono disposti secondo righe e colonne. Può essere utile pensare al dataframe esattamente come ad una normale tabella che si può creare in un foglio di calcolo (e.g., Excel) dove possiamo inserire i nostri dati. Dati in questo caso è volutamente generico poichè i dataframe, a differenza delle matrici, possono contenere nello stesso oggetto tipi diversi di dati (e.g., <em>nomi</em>, <em>date</em> e <em>numeri</em>).</p>
<p>The basic structure of a dataframe is thus the same as a matrix, but it allows us to include various data types in the same object, such as characters and numerical values. This enables us to store all the features of statistical units (e.g., numerical, categorical, nominal variables, etc.) that we aim to analyze later. A crucial point is that dataframes are designed to handle complex and heterogeneous data, typical in real data analysis. If you use other programming languages geared toward data analysis (e.g., Matlab), you’ll notice the lack of a powerful and intuitive object like the dataframe.</p>
<p>Generally, in a dataframe, rows represent statistical units (e.g., people or observations), and columns represent variables, which are properties measured on those units. However, there are two main dataframe formats depending on how the data is organized: <strong>wide</strong> dataframes and <strong>long</strong> dataframes. Let’s evaluate the difference between the two formats by considering data where, for each subject, we measure age, gender, and responses to three items in a questionnaire.</p>
<div id="wide-dataframe" class="section level4 unnumbered hasAnchor">
<h4>Wide Dataframe<a href="dataframe.html#wide-dataframe" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>In the <strong>wide</strong> format, each row of the dataframe represents a subject, and each of their responses or measured variables is reported in a different column. Even repeated responses to the same type of variable, such as questionnaire items, experimental trials, or the same variable measured at multiple time points are presented in different columns, so that whatever has been collected for a single participant is reported in one and a single row. The wide format is arguably the most familiar to researchers who routinely perform analyses with the SPSS software. In Table <a href="dataframe.html#tab:table-wide-db">10.1</a>, some example data is presented in wide format: notice how responses to different items are reported in multiple columns.</p>
<table class="table table-striped table-hover table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:table-wide-db">Table 10.1: </span><span id="tab:table-wide-db">Table 10.2: </span>Dataframe in wide format
</caption>
<thead>
<tr>
<th style="text-align:center;">
Id
</th>
<th style="text-align:center;">
age
</th>
<th style="text-align:center;">
gender
</th>
<th style="text-align:center;">
item_1
</th>
<th style="text-align:center;">
item_2
</th>
<th style="text-align:center;">
item_3
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
subj_1
</td>
<td style="text-align:center;">
21
</td>
<td style="text-align:center;">
F
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
2
</td>
</tr>
<tr>
<td style="text-align:center;">
subj_2
</td>
<td style="text-align:center;">
23
</td>
<td style="text-align:center;">
M
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:center;">
subj_3
</td>
<td style="text-align:center;">
19
</td>
<td style="text-align:center;">
F
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
1
</td>
</tr>
</tbody>
</table>
<p>We see that each subject is identified by a code in the <em>Id</em> variable, and their responses to the three items are reported in three different variables <em>item_1</em>, <em>item_2</em>, and <em>item_3</em>.</p>
</div>
<div id="long-dataframe" class="section level4 unnumbered hasAnchor">
<h4>Long Dataframe<a href="dataframe.html#long-dataframe" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>In the <strong>long</strong> format, each row represents a single observation. Therefore, the data for each subject is spread across multiple rows, and variables that don’t change across observations are repeated. In Table <a href="dataframe.html#tab:table-long-db">10.3</a>, the example data is presented in long format.</p>
<table class="table table-striped table-hover table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:table-long-db">Table 10.3: </span><span id="tab:table-long-db">Table 10.4: </span>Dataframe in long format
</caption>
<thead>
<tr>
<th style="text-align:center;">
Id
</th>
<th style="text-align:center;">
age
</th>
<th style="text-align:center;">
gender
</th>
<th style="text-align:center;">
item
</th>
<th style="text-align:center;">
response
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
subj_1
</td>
<td style="text-align:center;">
21
</td>
<td style="text-align:center;">
F
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
2
</td>
</tr>
<tr>
<td style="text-align:center;">
subj_1
</td>
<td style="text-align:center;">
21
</td>
<td style="text-align:center;">
F
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
1
</td>
</tr>
<tr>
<td style="text-align:center;">
subj_1
</td>
<td style="text-align:center;">
21
</td>
<td style="text-align:center;">
F
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1
</td>
</tr>
<tr>
<td style="text-align:center;">
subj_2
</td>
<td style="text-align:center;">
23
</td>
<td style="text-align:center;">
M
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:center;">
subj_2
</td>
<td style="text-align:center;">
23
</td>
<td style="text-align:center;">
M
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
2
</td>
</tr>
<tr>
<td style="text-align:center;">
subj_2
</td>
<td style="text-align:center;">
23
</td>
<td style="text-align:center;">
M
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1
</td>
</tr>
<tr>
<td style="text-align:center;">
subj_3
</td>
<td style="text-align:center;">
19
</td>
<td style="text-align:center;">
F
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
2
</td>
</tr>
<tr>
<td style="text-align:center;">
subj_3
</td>
<td style="text-align:center;">
19
</td>
<td style="text-align:center;">
F
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:center;">
subj_3
</td>
<td style="text-align:center;">
19
</td>
<td style="text-align:center;">
F
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1
</td>
</tr>
</tbody>
</table>
<p>We observe that each subject’s responses are spread across multiple rows. The characteristics that do not vary are repeated in each row (<em>Id</em>, <em>age</em>, and <em>gender</em>), while the responses to the items are recorded using two columns: <em>item</em>, which represents the item number, and response, which records the subject’s actual response to that specific item.</p>
<div class="tip" title="Long or Wide?">
<p>Long and wide data formats have different properties, especially in terms of usage. The type of data and the final result are the same; however, some software or R packages work only with datasets organized in a certain way (e.g., <code>lme4</code> package for fitting mixed-models and <code>ggplot2</code> for data visualization mostly require <strong>long</strong> format dataframes, while <code>lavaan</code> package for structural equation modeling mostly require <strong>wide</strong> format dataframes.)</p>
<p>There isn’t a “correct” or “incorrect” format; it depends on the type of analysis and the software or package you’re using. Some operations or analyses require the dataset in <strong>long</strong> format, while others require it in <strong>wide</strong> format.</p>
<p>However, it’s advisable to become accustomed to thinking in <strong>long</strong> format because most modern data analysis and visualization packages require the data in this structure. There are also functions for quickly switching from one format to another (e.g., the <code>reshape()</code> function).</p>
</div>
<p>Note that in the previous examples, we used both numeric and character columns. This wasn’t possible with matrices. However, keep in mind that, just like matrices, dataframes require that all columns (variables) have the same number of elements.</p>
<p>Now we’ll see how to create dataframes in R, how to perform common selection operations, and describe some simple manipulations with dataframes. As we’ll see, there are many similarities between using dataframes and matrices. When necessary, we’ll refer to the previous chapter to highlight common aspects and differences between these two data structures.</p>
</div>
<div id="creating-a-dataframe" class="section level2 hasAnchor" number="10.1">
<h2><span class="header-section-number">10.1</span> Creating a dataframe<a href="dataframe.html#creating-a-dataframe" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In most cases, you will probably upload existing data (e.g., from a <code>.csv</code> file containing some collected experimental data) rather than creating a dataframe from scratch in R. However, let’s now see how to create a new dataframe. The command to create a dataframe is <code>data.frame()</code>:</p>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="dataframe.html#cb197-1" tabindex="-1"></a>nome_df <span class="ot">=</span> <span class="fu">data.frame</span>(</span>
<span id="cb197-2"><a href="dataframe.html#cb197-2" tabindex="-1"></a>  <span class="at">variable1 =</span> <span class="fu">c</span>(...),</span>
<span id="cb197-3"><a href="dataframe.html#cb197-3" tabindex="-1"></a>  <span class="at">variable2 =</span> <span class="fu">c</span>(...),</span>
<span id="cb197-4"><a href="dataframe.html#cb197-4" tabindex="-1"></a>  ...)</span></code></pre></div>
<p>Creating a dataframe is slightly different from matrices. Intuitively, it’s like combining several columns (where one may contain names, another dates, and so on) rather than inserting values by row or column as in matrices. In fact, to create a <code>dataframe</code>, you need to specify the columns one by one, indicating <code>column_name = values</code> within the <code>data.frame()</code> command. Let’s see an example in R:</p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="dataframe.html#cb198-1" tabindex="-1"></a>my_data <span class="ot">=</span> <span class="fu">data.frame</span>(</span>
<span id="cb198-2"><a href="dataframe.html#cb198-2" tabindex="-1"></a>  <span class="at">Id =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>),</span>
<span id="cb198-3"><a href="dataframe.html#cb198-3" tabindex="-1"></a>  <span class="at">names =</span> <span class="fu">c</span>(<span class="st">&quot;Alice&quot;</span>, <span class="st">&quot;Bruno&quot;</span>, <span class="st">&quot;Carla&quot;</span>, <span class="st">&quot;Diego&quot;</span>, <span class="st">&quot;Elisa&quot;</span>),</span>
<span id="cb198-4"><a href="dataframe.html#cb198-4" tabindex="-1"></a>  <span class="at">gender =</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="st">&quot;F&quot;</span>,<span class="st">&quot;M&quot;</span>,<span class="st">&quot;F&quot;</span>, <span class="st">&quot;M&quot;</span>, <span class="st">&quot;F&quot;</span>)),</span>
<span id="cb198-5"><a href="dataframe.html#cb198-5" tabindex="-1"></a>  <span class="at">age =</span> <span class="fu">c</span>(<span class="dv">22</span>, <span class="dv">25</span>, <span class="dv">23</span>, <span class="dv">22</span>, <span class="dv">24</span>),</span>
<span id="cb198-6"><a href="dataframe.html#cb198-6" tabindex="-1"></a>  <span class="at">faculty =</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="st">&quot;Psychology&quot;</span>, <span class="st">&quot;Engineering&quot;</span>, <span class="st">&quot;Medicine&quot;</span>, <span class="st">&quot;Arts&quot;</span>, <span class="st">&quot;Psychology&quot;</span>))</span>
<span id="cb198-7"><a href="dataframe.html#cb198-7" tabindex="-1"></a>)</span>
<span id="cb198-8"><a href="dataframe.html#cb198-8" tabindex="-1"></a></span>
<span id="cb198-9"><a href="dataframe.html#cb198-9" tabindex="-1"></a>my_data</span>
<span id="cb198-10"><a href="dataframe.html#cb198-10" tabindex="-1"></a><span class="do">##   Id names gender age     faculty</span></span>
<span id="cb198-11"><a href="dataframe.html#cb198-11" tabindex="-1"></a><span class="do">## 1  1 Alice      F  22  Psychology</span></span>
<span id="cb198-12"><a href="dataframe.html#cb198-12" tabindex="-1"></a><span class="do">## 2  2 Bruno      M  25 Engineering</span></span>
<span id="cb198-13"><a href="dataframe.html#cb198-13" tabindex="-1"></a><span class="do">## 3  3 Carla      F  23    Medicine</span></span>
<span id="cb198-14"><a href="dataframe.html#cb198-14" tabindex="-1"></a><span class="do">## 4  4 Diego      M  22        Arts</span></span>
<span id="cb198-15"><a href="dataframe.html#cb198-15" tabindex="-1"></a><span class="do">## 5  5 Elisa      F  24  Psychology</span></span></code></pre></div>
<p>In this case, we’ve created a hypothetical dataframe where each row represents a subject, and each column represents a certain characteristic of that subject, like gender, age, and so on.</p>
<div class="tip" title="ID">
<p>It’s always recommended to define a column (e.g., <code>Id</code>) where you assign a unique identifier to each subject. This allows you to identify them without risking errors. For example, using a name (or even first and last names) may not be ideal because multiple people could have the same name, making it difficult to distinguish between them. While this may not seem strictly needed when using <em>wide</em> dataframes, as different rows always represent different individuals, that becomes crucial when using <em>long</em> dataframes, as multiple rows may or may not represent data from the same individual.</p>
</div>
<div class="warning" title="stringsAsFactors">
<p>A character variable within a DataFrame is considered by default as a simple sequence of characters. You can specify the argument <code>stringsAsFactors = TRUE</code> to automatically convert all character variables to categorical variables (see Chapter <a href="factor.html#factor">8</a></p>
<p>Note that the default behavior depends on the version of R. Versions prior to R 4.0 had <code>stringsAsFactors = TRUE</code> by default, while from R 4.0 onwards, the default is <code>stringsAsFactors = FALSE</code>. So, pay attention when using code written before version 4.0.</p>
</div>
<div id="exercises-9" class="section level3 unnumbered hasAnchor">
<h3>Exercises<a href="dataframe.html#exercises-9" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Perform the following exercises (<a href="https://github.com/psicostat/Introduction2R/blob/master/exercises/chapter-10-dataframe.R">solutions</a>):</p>
<ol style="list-style-type: decimal">
<li>Create the <code>data_wide</code> dataframe shown in Table <a href="dataframe.html#tab:table-wide-db">10.1</a>.</li>
<li>Create the <code>data_long</code> dataframe shown in Table <a href="dataframe.html#tab:table-long-db">10.3</a>.</li>
</ol>
</div>
</div>
<div id="sel-df" class="section level2 hasAnchor" number="10.2">
<h2><span class="header-section-number">10.2</span> Selecting Elements<a href="dataframe.html#sel-df" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To select one or more values from a dataframe, you can use row and column indices within square brackets, similar to matrices:</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="dataframe.html#cb199-1" tabindex="-1"></a>dataframe_name[<span class="sc">&lt;</span>row<span class="sc">-</span>index<span class="sc">&gt;</span>, <span class="sc">&lt;</span>column<span class="sc">-</span>index<span class="sc">&gt;</span>]</span></code></pre></div>
<p>Remember that the order <code>[&lt;row-index&gt;, &lt;column-index&gt;]</code> is fixed and must be followed for the selection to work correctly. You can perform various types of selections depending on your needs, using the same procedures seen for matrices. For example, using the <code>my_data</code> dataframe created earlier, we can select:</p>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="dataframe.html#cb200-1" tabindex="-1"></a>my_data</span>
<span id="cb200-2"><a href="dataframe.html#cb200-2" tabindex="-1"></a><span class="do">##    Id    names gender age     faculty</span></span>
<span id="cb200-3"><a href="dataframe.html#cb200-3" tabindex="-1"></a><span class="do">## 1   1    Alice      F  22  Psychology</span></span>
<span id="cb200-4"><a href="dataframe.html#cb200-4" tabindex="-1"></a><span class="do">## 2   2    Bruno      M  25 Engineering</span></span>
<span id="cb200-5"><a href="dataframe.html#cb200-5" tabindex="-1"></a><span class="do">## 3   3    Carla      F  23    Medicine</span></span>
<span id="cb200-6"><a href="dataframe.html#cb200-6" tabindex="-1"></a><span class="do">## 4   4    Diego      M  22        Arts</span></span>
<span id="cb200-7"><a href="dataframe.html#cb200-7" tabindex="-1"></a><span class="do">## 5   5    Elisa      F  24  Psychology</span></span>
<span id="cb200-8"><a href="dataframe.html#cb200-8" tabindex="-1"></a><span class="do">## 6   6 Fabrizio      M  35        Arts</span></span>
<span id="cb200-9"><a href="dataframe.html#cb200-9" tabindex="-1"></a><span class="do">## 7   7   Gloria      F  26 Engineering</span></span>
<span id="cb200-10"><a href="dataframe.html#cb200-10" tabindex="-1"></a><span class="do">## 8   8   Herman      M  20  Psychology</span></span>
<span id="cb200-11"><a href="dataframe.html#cb200-11" tabindex="-1"></a><span class="do">## 9   9    Irene      F  23  Statistics</span></span>
<span id="cb200-12"><a href="dataframe.html#cb200-12" tabindex="-1"></a><span class="do">## 10 10     Luca      M  22 Engineering</span></span>
<span id="cb200-13"><a href="dataframe.html#cb200-13" tabindex="-1"></a></span>
<span id="cb200-14"><a href="dataframe.html#cb200-14" tabindex="-1"></a><span class="co"># Value in 3rd row and 2nd column</span></span>
<span id="cb200-15"><a href="dataframe.html#cb200-15" tabindex="-1"></a>my_data[<span class="dv">3</span>,<span class="dv">4</span>]</span>
<span id="cb200-16"><a href="dataframe.html#cb200-16" tabindex="-1"></a><span class="do">## [1] 23</span></span>
<span id="cb200-17"><a href="dataframe.html#cb200-17" tabindex="-1"></a></span>
<span id="cb200-18"><a href="dataframe.html#cb200-18" tabindex="-1"></a><span class="co"># All variables of the 1st and 3rd rows</span></span>
<span id="cb200-19"><a href="dataframe.html#cb200-19" tabindex="-1"></a>my_data[<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>), ]</span>
<span id="cb200-20"><a href="dataframe.html#cb200-20" tabindex="-1"></a><span class="do">##   Id names gender age     faculty</span></span>
<span id="cb200-21"><a href="dataframe.html#cb200-21" tabindex="-1"></a><span class="do">## 2  2 Bruno      M  25 Engineering</span></span>
<span id="cb200-22"><a href="dataframe.html#cb200-22" tabindex="-1"></a><span class="do">## 3  3 Carla      F  23    Medicine</span></span>
<span id="cb200-23"><a href="dataframe.html#cb200-23" tabindex="-1"></a></span>
<span id="cb200-24"><a href="dataframe.html#cb200-24" tabindex="-1"></a><span class="co"># All values of the 5th variable</span></span>
<span id="cb200-25"><a href="dataframe.html#cb200-25" tabindex="-1"></a>my_data[ , <span class="dv">5</span>]</span>
<span id="cb200-26"><a href="dataframe.html#cb200-26" tabindex="-1"></a><span class="do">##  [1] Psychology  Engineering Medicine    Arts        Psychology  Arts       </span></span>
<span id="cb200-27"><a href="dataframe.html#cb200-27" tabindex="-1"></a><span class="do">##  [7] Engineering Psychology  Statistics  Engineering</span></span>
<span id="cb200-28"><a href="dataframe.html#cb200-28" tabindex="-1"></a><span class="do">## Levels: Arts Engineering Medicine Psychology Statistics</span></span>
<span id="cb200-29"><a href="dataframe.html#cb200-29" tabindex="-1"></a></span>
<span id="cb200-30"><a href="dataframe.html#cb200-30" tabindex="-1"></a><span class="co"># Values of the 2nd and 4th variables for the 3rd and 5th rows</span></span>
<span id="cb200-31"><a href="dataframe.html#cb200-31" tabindex="-1"></a>my_data[<span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">5</span>), <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">4</span>)]</span>
<span id="cb200-32"><a href="dataframe.html#cb200-32" tabindex="-1"></a><span class="do">##   names age</span></span>
<span id="cb200-33"><a href="dataframe.html#cb200-33" tabindex="-1"></a><span class="do">## 3 Carla  23</span></span>
<span id="cb200-34"><a href="dataframe.html#cb200-34" tabindex="-1"></a><span class="do">## 5 Elisa  24</span></span></code></pre></div>
<p>However, when working with dataframes, it’s more common to refer to the column names and use logical conditions to select values of interest.</p>
<div id="selecting-columns-by-variable-names" class="section level4 unnumbered hasAnchor">
<h4>Selecting Columns by Variable Names<a href="dataframe.html#selecting-columns-by-variable-names" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>One significant difference between matrices and dataframes is that you can access columns using the <code>$</code> operator and the column name, using the following syntax:</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="dataframe.html#cb201-1" tabindex="-1"></a>dataframe_name<span class="sc">$</span>variable_name</span></code></pre></div>
<p>This allows you to access that specific column directly without using indices and square brackets. For example:</p>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb202-1"><a href="dataframe.html#cb202-1" tabindex="-1"></a><span class="co"># Select the &quot;names&quot; variable</span></span>
<span id="cb202-2"><a href="dataframe.html#cb202-2" tabindex="-1"></a>my_data<span class="sc">$</span>names</span>
<span id="cb202-3"><a href="dataframe.html#cb202-3" tabindex="-1"></a><span class="do">##  [1] &quot;Alice&quot;    &quot;Bruno&quot;    &quot;Carla&quot;    &quot;Diego&quot;    &quot;Elisa&quot;    &quot;Fabrizio&quot;</span></span>
<span id="cb202-4"><a href="dataframe.html#cb202-4" tabindex="-1"></a><span class="do">##  [7] &quot;Gloria&quot;   &quot;Herman&quot;   &quot;Irene&quot;    &quot;Luca&quot;</span></span>
<span id="cb202-5"><a href="dataframe.html#cb202-5" tabindex="-1"></a></span>
<span id="cb202-6"><a href="dataframe.html#cb202-6" tabindex="-1"></a><span class="co"># Select the &quot;faculty&quot; variable</span></span>
<span id="cb202-7"><a href="dataframe.html#cb202-7" tabindex="-1"></a>my_data<span class="sc">$</span>faculty</span>
<span id="cb202-8"><a href="dataframe.html#cb202-8" tabindex="-1"></a><span class="do">##  [1] Psychology  Engineering Medicine    Arts        Psychology  Arts       </span></span>
<span id="cb202-9"><a href="dataframe.html#cb202-9" tabindex="-1"></a><span class="do">##  [7] Engineering Psychology  Statistics  Engineering</span></span>
<span id="cb202-10"><a href="dataframe.html#cb202-10" tabindex="-1"></a><span class="do">## Levels: Arts Engineering Medicine Psychology Statistics</span></span></code></pre></div>
<p>Alternatively, you can use the usual square bracket selection method by specifying the column names instead of column indices. This allows you to select multiple variables at once. For example:</p>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb203-1"><a href="dataframe.html#cb203-1" tabindex="-1"></a><span class="co"># Select only the &quot;names&quot; variable</span></span>
<span id="cb203-2"><a href="dataframe.html#cb203-2" tabindex="-1"></a>my_data[ , <span class="st">&quot;names&quot;</span>]</span>
<span id="cb203-3"><a href="dataframe.html#cb203-3" tabindex="-1"></a><span class="do">##  [1] &quot;Alice&quot;    &quot;Bruno&quot;    &quot;Carla&quot;    &quot;Diego&quot;    &quot;Elisa&quot;    &quot;Fabrizio&quot;</span></span>
<span id="cb203-4"><a href="dataframe.html#cb203-4" tabindex="-1"></a><span class="do">##  [7] &quot;Gloria&quot;   &quot;Herman&quot;   &quot;Irene&quot;    &quot;Luca&quot;</span></span>
<span id="cb203-5"><a href="dataframe.html#cb203-5" tabindex="-1"></a></span>
<span id="cb203-6"><a href="dataframe.html#cb203-6" tabindex="-1"></a><span class="co"># Select the &quot;names&quot;, &quot;gender&quot;, and &quot;faculty&quot; variables</span></span>
<span id="cb203-7"><a href="dataframe.html#cb203-7" tabindex="-1"></a>my_data[, <span class="fu">c</span>(<span class="st">&quot;names&quot;</span>, <span class="st">&quot;gender&quot;</span>, <span class="st">&quot;faculty&quot;</span>)]</span>
<span id="cb203-8"><a href="dataframe.html#cb203-8" tabindex="-1"></a><span class="do">##       names gender     faculty</span></span>
<span id="cb203-9"><a href="dataframe.html#cb203-9" tabindex="-1"></a><span class="do">## 1     Alice      F  Psychology</span></span>
<span id="cb203-10"><a href="dataframe.html#cb203-10" tabindex="-1"></a><span class="do">## 2     Bruno      M Engineering</span></span>
<span id="cb203-11"><a href="dataframe.html#cb203-11" tabindex="-1"></a><span class="do">## 3     Carla      F    Medicine</span></span>
<span id="cb203-12"><a href="dataframe.html#cb203-12" tabindex="-1"></a><span class="do">## 4     Diego      M        Arts</span></span>
<span id="cb203-13"><a href="dataframe.html#cb203-13" tabindex="-1"></a><span class="do">## 5     Elisa      F  Psychology</span></span>
<span id="cb203-14"><a href="dataframe.html#cb203-14" tabindex="-1"></a><span class="do">## 6  Fabrizio      M        Arts</span></span>
<span id="cb203-15"><a href="dataframe.html#cb203-15" tabindex="-1"></a><span class="do">## 7    Gloria      F Engineering</span></span>
<span id="cb203-16"><a href="dataframe.html#cb203-16" tabindex="-1"></a><span class="do">## 8    Herman      M  Psychology</span></span>
<span id="cb203-17"><a href="dataframe.html#cb203-17" tabindex="-1"></a><span class="do">## 9     Irene      F  Statistics</span></span>
<span id="cb203-18"><a href="dataframe.html#cb203-18" tabindex="-1"></a><span class="do">## 10     Luca      M Engineering</span></span></code></pre></div>
<p>Note that the variable names must be provided as strings.</p>
</div>
<div id="selecting-rows-with-logical-conditions" class="section level4 unnumbered hasAnchor">
<h4>Selecting Rows with Logical Conditions<a href="dataframe.html#selecting-rows-with-logical-conditions" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We’ve seen earlier how to construct logical propositions to select only values that meet a certain condition in the case of vectors and matrices. Now, this function becomes particularly useful as it allows us to <em>query</em> the dataframe in a simple and intuitive way. By using a logical condition, we can <em>filter</em> the observations that satisfy a given condition and retrieve only the information of interest.</p>
<p>In the canonical syntax <code>[&lt;row-index&gt;, &lt;column-index&gt;]</code>, the row indices are replaced with a logical condition to filter the rows, and the column indices are replaced with the names of the variables of interest. We use the following syntax:</p>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="dataframe.html#cb204-1" tabindex="-1"></a>dataframe_name[<span class="sc">&lt;</span>logical_condition_rows<span class="sc">&gt;</span>, <span class="sc">&lt;</span>variable_names<span class="sc">&gt;</span>]</span></code></pre></div>
<p>Here are some examples of selection:</p>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb205-1"><a href="dataframe.html#cb205-1" tabindex="-1"></a><span class="co"># All data for &quot;Diego&quot; (Id == 4)</span></span>
<span id="cb205-2"><a href="dataframe.html#cb205-2" tabindex="-1"></a>my_data[my_data<span class="sc">$</span>Id <span class="sc">==</span> <span class="dv">4</span> , ]</span>
<span id="cb205-3"><a href="dataframe.html#cb205-3" tabindex="-1"></a><span class="do">##   Id names gender age faculty</span></span>
<span id="cb205-4"><a href="dataframe.html#cb205-4" tabindex="-1"></a><span class="do">## 4  4 Diego      M  22    Arts</span></span>
<span id="cb205-5"><a href="dataframe.html#cb205-5" tabindex="-1"></a></span>
<span id="cb205-6"><a href="dataframe.html#cb205-6" tabindex="-1"></a><span class="co"># All data for females</span></span>
<span id="cb205-7"><a href="dataframe.html#cb205-7" tabindex="-1"></a>my_data[my_data<span class="sc">$</span>gender <span class="sc">==</span> <span class="st">&quot;F&quot;</span> , ]</span>
<span id="cb205-8"><a href="dataframe.html#cb205-8" tabindex="-1"></a><span class="do">##   Id  names gender age     faculty</span></span>
<span id="cb205-9"><a href="dataframe.html#cb205-9" tabindex="-1"></a><span class="do">## 1  1  Alice      F  22  Psychology</span></span>
<span id="cb205-10"><a href="dataframe.html#cb205-10" tabindex="-1"></a><span class="do">## 3  3  Carla      F  23    Medicine</span></span>
<span id="cb205-11"><a href="dataframe.html#cb205-11" tabindex="-1"></a><span class="do">## 5  5  Elisa      F  24  Psychology</span></span>
<span id="cb205-12"><a href="dataframe.html#cb205-12" tabindex="-1"></a><span class="do">## 7  7 Gloria      F  26 Engineering</span></span>
<span id="cb205-13"><a href="dataframe.html#cb205-13" tabindex="-1"></a><span class="do">## 9  9  Irene      F  23  Statistics</span></span>
<span id="cb205-14"><a href="dataframe.html#cb205-14" tabindex="-1"></a></span>
<span id="cb205-15"><a href="dataframe.html#cb205-15" tabindex="-1"></a><span class="co"># Faculties of subjects older than 24 years</span></span>
<span id="cb205-16"><a href="dataframe.html#cb205-16" tabindex="-1"></a>my_data[my_data<span class="sc">$</span>age <span class="sc">&gt;</span> <span class="dv">24</span> , <span class="fu">c</span>(<span class="st">&quot;age&quot;</span>, <span class="st">&quot;faculty&quot;</span>)]</span>
<span id="cb205-17"><a href="dataframe.html#cb205-17" tabindex="-1"></a><span class="do">##   age     faculty</span></span>
<span id="cb205-18"><a href="dataframe.html#cb205-18" tabindex="-1"></a><span class="do">## 2  25 Engineering</span></span>
<span id="cb205-19"><a href="dataframe.html#cb205-19" tabindex="-1"></a><span class="do">## 6  35        Arts</span></span>
<span id="cb205-20"><a href="dataframe.html#cb205-20" tabindex="-1"></a><span class="do">## 7  26 Engineering</span></span></code></pre></div>
<p>Note that when defining a logical condition using the dataframe’s variables, it’s still necessary to include the dataframe name. In the previous example, we would have encountered an error by simply using <code>age &gt; 24</code>, as this would refer to the object <code>age</code> (which doesn’t exist), not the <code>age</code> variable contained in <code>my_data</code>.</p>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb206-1"><a href="dataframe.html#cb206-1" tabindex="-1"></a>my_data[age <span class="sc">&gt;</span> <span class="dv">24</span> , <span class="fu">c</span>(<span class="st">&quot;age&quot;</span>, <span class="st">&quot;faculty&quot;</span>)]</span>
<span id="cb206-2"><a href="dataframe.html#cb206-2" tabindex="-1"></a><span class="do">## Error in eval(expr, envir, enclos): object &#39;age&#39; not found</span></span></code></pre></div>
<p>Similarly to what we saw with vectors, using the condition <code>my_data$age &gt; 24</code> returns a vector of <code>TRUE</code> and <code>FALSE</code> values depending on whether the condition is met or not.</p>
<p>By using logical operators <strong>AND</strong> (<code>&amp;</code>), <strong>OR</strong> (<code>|</code>), and <strong>NOT</strong> (<code>!</code>), we can combine multiple logical operations to create more complex, yet still intuitive, indexing queries. For example, to select “subjects between 20 and 25 years old enrolled in psychology,” we would write:</p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb207-1"><a href="dataframe.html#cb207-1" tabindex="-1"></a>my_data[my_data<span class="sc">$</span>age <span class="sc">&gt;=</span> <span class="dv">20</span> <span class="sc">&amp;</span> my_data<span class="sc">$</span>age <span class="sc">&lt;=</span><span class="dv">25</span> <span class="sc">&amp;</span> my_data<span class="sc">$</span>faculty <span class="sc">==</span> <span class="st">&quot;Psychology&quot;</span>, ]</span>
<span id="cb207-2"><a href="dataframe.html#cb207-2" tabindex="-1"></a><span class="do">##   Id  names gender age    faculty</span></span>
<span id="cb207-3"><a href="dataframe.html#cb207-3" tabindex="-1"></a><span class="do">## 1  1  Alice      F  22 Psychology</span></span>
<span id="cb207-4"><a href="dataframe.html#cb207-4" tabindex="-1"></a><span class="do">## 5  5  Elisa      F  24 Psychology</span></span>
<span id="cb207-5"><a href="dataframe.html#cb207-5" tabindex="-1"></a><span class="do">## 8  8 Herman      M  20 Psychology</span></span></code></pre></div>
<p>By using this indexing method, we can appreciate the true power of dataframes. We now have a very simple and intuitive method for working with complex data structures that contain different data types.</p>
<div class="design" title="Selection Output">
<p>Two important aspects regarding the result of a selection are the type of output obtained and how to save it.</p>
<div id="output-type" class="section level4 unnumbered hasAnchor">
<h4>Output Type<a href="dataframe.html#output-type" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Similarly to matrices, selection commands do not always return the same type of object. When we select a single variable, the result is a vector, while selecting two or more variables returns a dataframe.</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="dataframe.html#cb208-1" tabindex="-1"></a><span class="co"># Single variable</span></span>
<span id="cb208-2"><a href="dataframe.html#cb208-2" tabindex="-1"></a><span class="fu">class</span>(my_data<span class="sc">$</span>age)</span>
<span id="cb208-3"><a href="dataframe.html#cb208-3" tabindex="-1"></a><span class="do">## [1] &quot;numeric&quot;</span></span>
<span id="cb208-4"><a href="dataframe.html#cb208-4" tabindex="-1"></a></span>
<span id="cb208-5"><a href="dataframe.html#cb208-5" tabindex="-1"></a><span class="co"># Multiple variables</span></span>
<span id="cb208-6"><a href="dataframe.html#cb208-6" tabindex="-1"></a><span class="fu">class</span>(my_data[ , <span class="fu">c</span>(<span class="st">&quot;names&quot;</span>, <span class="st">&quot;age&quot;</span>)])</span>
<span id="cb208-7"><a href="dataframe.html#cb208-7" tabindex="-1"></a><span class="do">## [1] &quot;data.frame&quot;</span></span></code></pre></div>
</div>
<div id="saving-the-selection" class="section level4 unnumbered hasAnchor">
<h4>Saving the Selection<a href="dataframe.html#saving-the-selection" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>As with other types of objects, selection operations do not modify the original object. Therefore, if you wish to keep the changes, you need to save the result of the selection. It’s advisable to create a new object and not overwrite the original one, as this will allow you to make new selections or operations on the original data. It’s good practice to always keep one copy of the dataframe containing the original version of the data.</p>
</div>
</div>
</div>
<div id="advanced-selection-uses" class="section level3 hasAnchor" number="10.2.1">
<h3><span class="header-section-number">10.2.1</span> Advanced Selection Uses<a href="dataframe.html#advanced-selection-uses" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s now look at some advanced uses of selecting elements from a dataframe.</p>
<div id="modifying-elements" class="section level4 unnumbered hasAnchor">
<h4>Modifying Elements<a href="dataframe.html#modifying-elements" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Similar to other objects, we can modify values by selecting the old value in the dataframe and using the <code>=</code> (or <code>&lt;-</code>) operator to assign the new value.</p>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb209-1"><a href="dataframe.html#cb209-1" tabindex="-1"></a>my_data[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, ]</span>
<span id="cb209-2"><a href="dataframe.html#cb209-2" tabindex="-1"></a><span class="do">##   Id names gender age     faculty</span></span>
<span id="cb209-3"><a href="dataframe.html#cb209-3" tabindex="-1"></a><span class="do">## 1  1 Alice      F  22  Psychology</span></span>
<span id="cb209-4"><a href="dataframe.html#cb209-4" tabindex="-1"></a><span class="do">## 2  2 Bruno      M  25 Engineering</span></span>
<span id="cb209-5"><a href="dataframe.html#cb209-5" tabindex="-1"></a><span class="do">## 3  3 Carla      F  23    Medicine</span></span>
<span id="cb209-6"><a href="dataframe.html#cb209-6" tabindex="-1"></a><span class="do">## 4  4 Diego      M  22        Arts</span></span>
<span id="cb209-7"><a href="dataframe.html#cb209-7" tabindex="-1"></a><span class="do">## 5  5 Elisa      F  24  Psychology</span></span>
<span id="cb209-8"><a href="dataframe.html#cb209-8" tabindex="-1"></a></span>
<span id="cb209-9"><a href="dataframe.html#cb209-9" tabindex="-1"></a><span class="co"># Replace the name in the 4th row with &quot;Davide&quot;</span></span>
<span id="cb209-10"><a href="dataframe.html#cb209-10" tabindex="-1"></a>my_data[<span class="dv">4</span>, <span class="st">&quot;names&quot;</span>] <span class="ot">=</span> <span class="st">&quot;Davide&quot;</span></span>
<span id="cb209-11"><a href="dataframe.html#cb209-11" tabindex="-1"></a></span>
<span id="cb209-12"><a href="dataframe.html#cb209-12" tabindex="-1"></a>my_data[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span>
<span id="cb209-13"><a href="dataframe.html#cb209-13" tabindex="-1"></a><span class="do">##    Id    names gender age     faculty</span></span>
<span id="cb209-14"><a href="dataframe.html#cb209-14" tabindex="-1"></a><span class="do">## 1   1    Alice      F  22  Psychology</span></span>
<span id="cb209-15"><a href="dataframe.html#cb209-15" tabindex="-1"></a><span class="do">## 2   2    Bruno      M  25 Engineering</span></span>
<span id="cb209-16"><a href="dataframe.html#cb209-16" tabindex="-1"></a><span class="do">## 3   3    Carla      F  23    Medicine</span></span>
<span id="cb209-17"><a href="dataframe.html#cb209-17" tabindex="-1"></a><span class="do">## 4   4   Davide      M  22        Arts</span></span>
<span id="cb209-18"><a href="dataframe.html#cb209-18" tabindex="-1"></a><span class="do">## 5   5    Elisa      F  24  Psychology</span></span>
<span id="cb209-19"><a href="dataframe.html#cb209-19" tabindex="-1"></a><span class="do">## 6   6 Fabrizio      M  35        Arts</span></span>
<span id="cb209-20"><a href="dataframe.html#cb209-20" tabindex="-1"></a><span class="do">## 7   7   Gloria      F  26 Engineering</span></span>
<span id="cb209-21"><a href="dataframe.html#cb209-21" tabindex="-1"></a><span class="do">## 8   8   Herman      M  20  Psychology</span></span>
<span id="cb209-22"><a href="dataframe.html#cb209-22" tabindex="-1"></a><span class="do">## 9   9    Irene      F  23  Statistics</span></span>
<span id="cb209-23"><a href="dataframe.html#cb209-23" tabindex="-1"></a><span class="do">## 10 10     Luca      M  22 Engineering</span></span></code></pre></div>
</div>
<div id="deleting-rows-or-columns-1" class="section level4 unnumbered hasAnchor">
<h4>Deleting Rows or Columns<a href="dataframe.html#deleting-rows-or-columns-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Similarly to matrices, to delete rows (or columns) from a dataframe, you need to indicate the row (or column) indices to delete within square brackets, preceded by the <code>-</code> (<em>minus</em>) operator. In the case of multiple rows (or columns), you can specify the minus sign only before the <code>c()</code> function.</p>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="dataframe.html#cb210-1" tabindex="-1"></a><span class="co"># Delete the &quot;gender&quot; and &quot;age&quot; variables</span></span>
<span id="cb210-2"><a href="dataframe.html#cb210-2" tabindex="-1"></a>my_data[ , <span class="fu">c</span>(<span class="st">&quot;gender&quot;</span>, <span class="st">&quot;age&quot;</span>)]</span>
<span id="cb210-3"><a href="dataframe.html#cb210-3" tabindex="-1"></a><span class="do">##    gender age</span></span>
<span id="cb210-4"><a href="dataframe.html#cb210-4" tabindex="-1"></a><span class="do">## 1       F  22</span></span>
<span id="cb210-5"><a href="dataframe.html#cb210-5" tabindex="-1"></a><span class="do">## 2       M  25</span></span>
<span id="cb210-6"><a href="dataframe.html#cb210-6" tabindex="-1"></a><span class="do">## 3       F  23</span></span>
<span id="cb210-7"><a href="dataframe.html#cb210-7" tabindex="-1"></a><span class="do">## 4       M  22</span></span>
<span id="cb210-8"><a href="dataframe.html#cb210-8" tabindex="-1"></a><span class="do">## 5       F  24</span></span>
<span id="cb210-9"><a href="dataframe.html#cb210-9" tabindex="-1"></a><span class="do">## 6       M  35</span></span>
<span id="cb210-10"><a href="dataframe.html#cb210-10" tabindex="-1"></a><span class="do">## 7       F  26</span></span>
<span id="cb210-11"><a href="dataframe.html#cb210-11" tabindex="-1"></a><span class="do">## 8       M  20</span></span>
<span id="cb210-12"><a href="dataframe.html#cb210-12" tabindex="-1"></a><span class="do">## 9       F  23</span></span>
<span id="cb210-13"><a href="dataframe.html#cb210-13" tabindex="-1"></a><span class="do">## 10      M  22</span></span>
<span id="cb210-14"><a href="dataframe.html#cb210-14" tabindex="-1"></a></span>
<span id="cb210-15"><a href="dataframe.html#cb210-15" tabindex="-1"></a><span class="co"># Delete the first 5 observations</span></span>
<span id="cb210-16"><a href="dataframe.html#cb210-16" tabindex="-1"></a>my_data[<span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>), ]</span>
<span id="cb210-17"><a href="dataframe.html#cb210-17" tabindex="-1"></a><span class="do">##    Id    names gender age     faculty</span></span>
<span id="cb210-18"><a href="dataframe.html#cb210-18" tabindex="-1"></a><span class="do">## 6   6 Fabrizio      M  35        Arts</span></span>
<span id="cb210-19"><a href="dataframe.html#cb210-19" tabindex="-1"></a><span class="do">## 7   7   Gloria      F  26 Engineering</span></span>
<span id="cb210-20"><a href="dataframe.html#cb210-20" tabindex="-1"></a><span class="do">## 8   8   Herman      M  20  Psychology</span></span>
<span id="cb210-21"><a href="dataframe.html#cb210-21" tabindex="-1"></a><span class="do">## 9   9    Irene      F  23  Statistics</span></span>
<span id="cb210-22"><a href="dataframe.html#cb210-22" tabindex="-1"></a><span class="do">## 10 10     Luca      M  22 Engineering</span></span>
<span id="cb210-23"><a href="dataframe.html#cb210-23" tabindex="-1"></a></span>
<span id="cb210-24"><a href="dataframe.html#cb210-24" tabindex="-1"></a><span class="co"># Delete the first 5 observations and the &quot;names&quot; variable</span></span>
<span id="cb210-25"><a href="dataframe.html#cb210-25" tabindex="-1"></a>my_data[<span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>), <span class="sc">-</span><span class="dv">3</span>]</span>
<span id="cb210-26"><a href="dataframe.html#cb210-26" tabindex="-1"></a><span class="do">##    Id    names age     faculty</span></span>
<span id="cb210-27"><a href="dataframe.html#cb210-27" tabindex="-1"></a><span class="do">## 6   6 Fabrizio  35        Arts</span></span>
<span id="cb210-28"><a href="dataframe.html#cb210-28" tabindex="-1"></a><span class="do">## 7   7   Gloria  26 Engineering</span></span>
<span id="cb210-29"><a href="dataframe.html#cb210-29" tabindex="-1"></a><span class="do">## 8   8   Herman  20  Psychology</span></span>
<span id="cb210-30"><a href="dataframe.html#cb210-30" tabindex="-1"></a><span class="do">## 9   9    Irene  23  Statistics</span></span>
<span id="cb210-31"><a href="dataframe.html#cb210-31" tabindex="-1"></a><span class="do">## 10 10     Luca  22 Engineering</span></span></code></pre></div>
<p>You can also exclude (and in a sense delete) information using logical operators such as <strong>NOT</strong> (<code>!</code>) and <strong>not equal to</strong> (<code>!=</code>):</p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="dataframe.html#cb211-1" tabindex="-1"></a><span class="co"># Select everything except psychology students</span></span>
<span id="cb211-2"><a href="dataframe.html#cb211-2" tabindex="-1"></a></span>
<span id="cb211-3"><a href="dataframe.html#cb211-3" tabindex="-1"></a><span class="co"># Method 1 (evaluate where &quot;faculty&quot; is not equal to &quot;Psychology&quot;)</span></span>
<span id="cb211-4"><a href="dataframe.html#cb211-4" tabindex="-1"></a>my_data[my_data<span class="sc">$</span>faculty <span class="sc">!=</span> <span class="st">&quot;Psychology&quot;</span>, ]</span>
<span id="cb211-5"><a href="dataframe.html#cb211-5" tabindex="-1"></a><span class="do">##    Id    names gender age     faculty</span></span>
<span id="cb211-6"><a href="dataframe.html#cb211-6" tabindex="-1"></a><span class="do">## 2   2    Bruno      M  25 Engineering</span></span>
<span id="cb211-7"><a href="dataframe.html#cb211-7" tabindex="-1"></a><span class="do">## 3   3    Carla      F  23    Medicine</span></span>
<span id="cb211-8"><a href="dataframe.html#cb211-8" tabindex="-1"></a><span class="do">## 4   4   Davide      M  22        Arts</span></span>
<span id="cb211-9"><a href="dataframe.html#cb211-9" tabindex="-1"></a><span class="do">## 6   6 Fabrizio      M  35        Arts</span></span>
<span id="cb211-10"><a href="dataframe.html#cb211-10" tabindex="-1"></a><span class="do">## 7   7   Gloria      F  26 Engineering</span></span>
<span id="cb211-11"><a href="dataframe.html#cb211-11" tabindex="-1"></a><span class="do">## 9   9    Irene      F  23  Statistics</span></span>
<span id="cb211-12"><a href="dataframe.html#cb211-12" tabindex="-1"></a><span class="do">## 10 10     Luca      M  22 Engineering</span></span>
<span id="cb211-13"><a href="dataframe.html#cb211-13" tabindex="-1"></a></span>
<span id="cb211-14"><a href="dataframe.html#cb211-14" tabindex="-1"></a><span class="co"># Modo 1 (evaluate where &quot;faculty&quot; is equal to &quot;Psychology&quot;, all preceded by &quot;NOT&quot;)</span></span>
<span id="cb211-15"><a href="dataframe.html#cb211-15" tabindex="-1"></a>my_data[<span class="sc">!</span>my_data<span class="sc">$</span>faculty <span class="sc">==</span> <span class="st">&quot;Psychology&quot;</span>, ]</span>
<span id="cb211-16"><a href="dataframe.html#cb211-16" tabindex="-1"></a><span class="do">##    Id    names gender age     faculty</span></span>
<span id="cb211-17"><a href="dataframe.html#cb211-17" tabindex="-1"></a><span class="do">## 2   2    Bruno      M  25 Engineering</span></span>
<span id="cb211-18"><a href="dataframe.html#cb211-18" tabindex="-1"></a><span class="do">## 3   3    Carla      F  23    Medicine</span></span>
<span id="cb211-19"><a href="dataframe.html#cb211-19" tabindex="-1"></a><span class="do">## 4   4   Davide      M  22        Arts</span></span>
<span id="cb211-20"><a href="dataframe.html#cb211-20" tabindex="-1"></a><span class="do">## 6   6 Fabrizio      M  35        Arts</span></span>
<span id="cb211-21"><a href="dataframe.html#cb211-21" tabindex="-1"></a><span class="do">## 7   7   Gloria      F  26 Engineering</span></span>
<span id="cb211-22"><a href="dataframe.html#cb211-22" tabindex="-1"></a><span class="do">## 9   9    Irene      F  23  Statistics</span></span>
<span id="cb211-23"><a href="dataframe.html#cb211-23" tabindex="-1"></a><span class="do">## 10 10     Luca      M  22 Engineering</span></span></code></pre></div>
<p>Note that the deletion operation is still a selection operation. Therefore, if you want to keep the changes, you need to save the result.</p>
<div class="warning" title="Be Careful When Deleting">
<p>Using the <code>-</code> operator is somewhat risky, especially if the object created (or overwritten) is then used in other operations. Deleting information, unless strictly necessary, is not a good practice. If you need to select part of the data, it’s always better to create a new dataframe (or a new object in general) while keeping a version of the original data available.</p>
</div>
</div>
</div>
<div id="exercises-10" class="section level3 unnumbered hasAnchor">
<h3>Exercises<a href="dataframe.html#exercises-10" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Referring to the <code>data_long</code> and <code>data_wide</code> dataframes created earlier, complete the following exercises
(<a href="https://github.com/psicostat/Introduction2R/blob/master/exercises/chapter-10-dataframe.R">solutions</a>):</p>
<ol style="list-style-type: decimal">
<li>Using <strong>numeric indices</strong> for rows and columns, select the data for the subject <code>subj_2</code> regarding the <code>item</code> and <code>response</code> variables from the <code>data_long</code> dataframe.</li>
<li>Perform the same selection as the previous exercise, but this time use a logical condition for the row indices and specify the column names directly.</li>
<li>In the <code>data_wide</code> dataframe, select the <code>Id</code> and <code>gender</code> variables for subjects who responded with 1 to the <code>item_1</code> variable.</li>
<li>In the <code>data_long</code> dataframe, select only the data for girls older than 20 years.</li>
<li>Remove the observations regarding <code>subj_2</code> and the <code>"gender"</code> variable from the <code>data_long</code> dataframe.</li>
</ol>
</div>
</div>
<div id="functions-and-operations-1" class="section level2 hasAnchor" number="10.3">
<h2><span class="header-section-number">10.3</span> Functions and Operations<a href="dataframe.html#functions-and-operations-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Now, let’s look at some commonly used functions and operations performed with dataframes (see Table <a href="dataframe.html#tab:table-df-functions">10.5</a>).</p>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:table-df-functions">Table 10.5: </span><span id="tab:table-df-functions">Table 10.6: </span>Functions and operations with dataframes
</caption>
<thead>
<tr>
<th style="text-align:left;">
Function
</th>
<th style="text-align:left;">
Description
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
nrow(nome_df)
</td>
<td style="text-align:left;">
Number of observations in the dataframe
</td>
</tr>
<tr>
<td style="text-align:left;">
ncol(nome_df)
</td>
<td style="text-align:left;">
Number of variables in the dataframe
</td>
</tr>
<tr>
<td style="text-align:left;">
colnames(nome_df)
</td>
<td style="text-align:left;">
Column names of the dataframe
</td>
</tr>
<tr>
<td style="text-align:left;">
rownames(nome_df)
</td>
<td style="text-align:left;">
Row names of the dataframe
</td>
</tr>
<tr>
<td style="text-align:left;">
nome_df &amp;lt;-&lt;br&gt; cbind(nome_df, dati) &lt;br&gt; nome_df$nome_var &amp;lt;-&lt;br&gt; dati
</td>
<td style="text-align:left;">
Add a new variable to the dataframe (must have the same number of rows)
</td>
</tr>
<tr>
<td style="text-align:left;">
nome_df &amp;lt;- rbind(nome_df, dati)
</td>
<td style="text-align:left;">
Add observations (new data must match the structure of the dataframe)
</td>
</tr>
<tr>
<td style="text-align:left;">
head(nome_df)
</td>
<td style="text-align:left;">
First rows of the dataframe
</td>
</tr>
<tr>
<td style="text-align:left;">
tail(nome_df)
</td>
<td style="text-align:left;">
Last rows of the dataframe
</td>
</tr>
<tr>
<td style="text-align:left;">
str(nome_df)
</td>
<td style="text-align:left;">
Structure of the dataframe
</td>
</tr>
<tr>
<td style="text-align:left;">
summary(nome_df)
</td>
<td style="text-align:left;">
Summary of the dataframe
</td>
</tr>
</tbody>
</table>
<p>We will now describe in detail some particular uses, considering an example of a reduced version of the <code>my_data</code> dataframe created earlier.</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="dataframe.html#cb212-1" tabindex="-1"></a>data_short <span class="ot">=</span> my_data[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, ]</span>
<span id="cb212-2"><a href="dataframe.html#cb212-2" tabindex="-1"></a>data_short</span>
<span id="cb212-3"><a href="dataframe.html#cb212-3" tabindex="-1"></a><span class="do">##   Id  names gender age     faculty</span></span>
<span id="cb212-4"><a href="dataframe.html#cb212-4" tabindex="-1"></a><span class="do">## 1  1  Alice      F  22  Psychology</span></span>
<span id="cb212-5"><a href="dataframe.html#cb212-5" tabindex="-1"></a><span class="do">## 2  2  Bruno      M  25 Engineering</span></span>
<span id="cb212-6"><a href="dataframe.html#cb212-6" tabindex="-1"></a><span class="do">## 3  3  Carla      F  23    Medicine</span></span>
<span id="cb212-7"><a href="dataframe.html#cb212-7" tabindex="-1"></a><span class="do">## 4  4 Davide      M  22        Arts</span></span>
<span id="cb212-8"><a href="dataframe.html#cb212-8" tabindex="-1"></a><span class="do">## 5  5  Elisa      F  24  Psychology</span></span></code></pre></div>
<div id="attributes-of-a-dataframe" class="section level3 hasAnchor" number="10.3.1">
<h3><span class="header-section-number">10.3.1</span> Attributes of a Dataframe<a href="dataframe.html#attributes-of-a-dataframe" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We saw in Chapter <a href="factor.html#attributes">8.1</a> that objects in R possess what are called <em>attributes</em>, useful information about the object itself, akin to <em>metadata</em>. We will now, similarly to matrices, evaluate the dimensions of a dataframe and the names of its rows and columns.</p>
<div id="dimensions-1" class="section level4 unnumbered hasAnchor">
<h4>Dimensions<a href="dataframe.html#dimensions-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Recall that a dataframe is a <strong>two-dimensional</strong> object consisting of rows and columns. To obtain the number of rows and columns in a dataframe, we can use the <code>nrow()</code> and <code>ncol()</code> functions, respectively.</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="dataframe.html#cb213-1" tabindex="-1"></a><span class="co"># Number of rows</span></span>
<span id="cb213-2"><a href="dataframe.html#cb213-2" tabindex="-1"></a><span class="fu">nrow</span>(my_data)</span>
<span id="cb213-3"><a href="dataframe.html#cb213-3" tabindex="-1"></a><span class="do">## [1] 10</span></span>
<span id="cb213-4"><a href="dataframe.html#cb213-4" tabindex="-1"></a></span>
<span id="cb213-5"><a href="dataframe.html#cb213-5" tabindex="-1"></a><span class="co"># Number of columns</span></span>
<span id="cb213-6"><a href="dataframe.html#cb213-6" tabindex="-1"></a><span class="fu">ncol</span>(my_data)</span>
<span id="cb213-7"><a href="dataframe.html#cb213-7" tabindex="-1"></a><span class="do">## [1] 5</span></span></code></pre></div>
<p>Alternatively, as with matrices, we can use the <code>dim()</code> function, which returns a vector with two values: the first representing the number of rows and the second the number of columns.</p>
</div>
<div id="row-and-column-names-1" class="section level4 unnumbered hasAnchor">
<h4>Row and Column Names<a href="dataframe.html#row-and-column-names-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Similarly to matrices, you can access the row and column names using the <code>rownames()</code> and <code>colnames()</code> functions, respectively. By default, dataframes require names only for the columns, while rows are assigned names based on their row indices. However, it’s possible to name rows with arbitrary values, although this is rarely used.</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="dataframe.html#cb214-1" tabindex="-1"></a><span class="co"># Check the current names</span></span>
<span id="cb214-2"><a href="dataframe.html#cb214-2" tabindex="-1"></a><span class="fu">rownames</span>(data_short)</span>
<span id="cb214-3"><a href="dataframe.html#cb214-3" tabindex="-1"></a><span class="do">## [1] &quot;1&quot; &quot;2&quot; &quot;3&quot; &quot;4&quot; &quot;5&quot;</span></span>
<span id="cb214-4"><a href="dataframe.html#cb214-4" tabindex="-1"></a><span class="fu">colnames</span>(data_short)</span>
<span id="cb214-5"><a href="dataframe.html#cb214-5" tabindex="-1"></a><span class="do">## [1] &quot;Id&quot;      &quot;names&quot;   &quot;gender&quot;  &quot;age&quot;     &quot;faculty&quot;</span></span></code></pre></div>
<p>To set row and/or column names, assign a character vector of the same length as the dimension you’re renaming to <code>rownames(dataframe_name)</code> or <code>colnames(dataframe_name)</code>.</p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="dataframe.html#cb215-1" tabindex="-1"></a><span class="co"># Assign names to the rows</span></span>
<span id="cb215-2"><a href="dataframe.html#cb215-2" tabindex="-1"></a><span class="fu">rownames</span>(data_short) <span class="ot">=</span> <span class="fu">paste0</span>(<span class="st">&quot;Subj_&quot;</span>, <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(data_short))</span>
<span id="cb215-3"><a href="dataframe.html#cb215-3" tabindex="-1"></a></span>
<span id="cb215-4"><a href="dataframe.html#cb215-4" tabindex="-1"></a><span class="co"># Assign names to the columns</span></span>
<span id="cb215-5"><a href="dataframe.html#cb215-5" tabindex="-1"></a><span class="fu">colnames</span>(data_short) <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;Id&quot;</span>, <span class="st">&quot;Name&quot;</span>, <span class="st">&quot;Gender&quot;</span>, <span class="st">&quot;Age&quot;</span>, <span class="st">&quot;Faculty&quot;</span>)</span>
<span id="cb215-6"><a href="dataframe.html#cb215-6" tabindex="-1"></a></span>
<span id="cb215-7"><a href="dataframe.html#cb215-7" tabindex="-1"></a>data_short</span>
<span id="cb215-8"><a href="dataframe.html#cb215-8" tabindex="-1"></a><span class="do">##        Id   Name Gender Age     Faculty</span></span>
<span id="cb215-9"><a href="dataframe.html#cb215-9" tabindex="-1"></a><span class="do">## Subj_1  1  Alice      F  22  Psychology</span></span>
<span id="cb215-10"><a href="dataframe.html#cb215-10" tabindex="-1"></a><span class="do">## Subj_2  2  Bruno      M  25 Engineering</span></span>
<span id="cb215-11"><a href="dataframe.html#cb215-11" tabindex="-1"></a><span class="do">## Subj_3  3  Carla      F  23    Medicine</span></span>
<span id="cb215-12"><a href="dataframe.html#cb215-12" tabindex="-1"></a><span class="do">## Subj_4  4 Davide      M  22        Arts</span></span>
<span id="cb215-13"><a href="dataframe.html#cb215-13" tabindex="-1"></a><span class="do">## Subj_5  5  Elisa      F  24  Psychology</span></span></code></pre></div>
<p>Finally, note that the <code>names()</code> function for dataframes is analogous to <code>colnames()</code>, and you can use <code>NULL</code> to remove, for example, row names.</p>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb216-1"><a href="dataframe.html#cb216-1" tabindex="-1"></a><span class="fu">names</span>(data_short)</span>
<span id="cb216-2"><a href="dataframe.html#cb216-2" tabindex="-1"></a><span class="do">## [1] &quot;Id&quot;      &quot;Name&quot;    &quot;Gender&quot;  &quot;Age&quot;     &quot;Faculty&quot;</span></span>
<span id="cb216-3"><a href="dataframe.html#cb216-3" tabindex="-1"></a></span>
<span id="cb216-4"><a href="dataframe.html#cb216-4" tabindex="-1"></a><span class="fu">rownames</span>(data_short) <span class="ot">=</span> <span class="cn">NULL</span></span>
<span id="cb216-5"><a href="dataframe.html#cb216-5" tabindex="-1"></a>data_short</span>
<span id="cb216-6"><a href="dataframe.html#cb216-6" tabindex="-1"></a><span class="do">##   Id   Name Gender Age     Faculty</span></span>
<span id="cb216-7"><a href="dataframe.html#cb216-7" tabindex="-1"></a><span class="do">## 1  1  Alice      F  22  Psychology</span></span>
<span id="cb216-8"><a href="dataframe.html#cb216-8" tabindex="-1"></a><span class="do">## 2  2  Bruno      M  25 Engineering</span></span>
<span id="cb216-9"><a href="dataframe.html#cb216-9" tabindex="-1"></a><span class="do">## 3  3  Carla      F  23    Medicine</span></span>
<span id="cb216-10"><a href="dataframe.html#cb216-10" tabindex="-1"></a><span class="do">## 4  4 Davide      M  22        Arts</span></span>
<span id="cb216-11"><a href="dataframe.html#cb216-11" tabindex="-1"></a><span class="do">## 5  5  Elisa      F  24  Psychology</span></span></code></pre></div>
</div>
</div>
<div id="merging-dataframes" class="section level3 hasAnchor" number="10.3.2">
<h3><span class="header-section-number">10.3.2</span> Merging Dataframes<a href="dataframe.html#merging-dataframes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Similarly to matrices, you can merge multiple dataframes using the <code>cbind()</code> and <code>rbind()</code> functions, with the same dimensionality requirements regarding rows and columns. However, for dataframes, you can also create a new column using the <code>$</code> operator. Let’s now describe these uses in detail.</p>
<div id="dataframename-new_var" class="section level4 unnumbered hasAnchor">
<h4><code>dataframe$name = new_var</code><a href="dataframe.html#dataframename-new_var" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>With the syntax <code>dataframe$name = new_var</code>, we add a new column named <code>name</code> to the dataframe, taking values from <code>new_var</code>. This new variable must have the same number of values as there are rows in the dataframe.</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="dataframe.html#cb217-1" tabindex="-1"></a><span class="co"># Add the &quot;average&quot; column</span></span>
<span id="cb217-2"><a href="dataframe.html#cb217-2" tabindex="-1"></a>data_short<span class="sc">$</span>Average <span class="ot">=</span> <span class="fu">c</span>(<span class="fl">27.5</span>, <span class="fl">23.6</span>, <span class="fl">28.3</span>, <span class="fl">29.2</span>, <span class="fl">24.8</span>)</span>
<span id="cb217-3"><a href="dataframe.html#cb217-3" tabindex="-1"></a></span>
<span id="cb217-4"><a href="dataframe.html#cb217-4" tabindex="-1"></a><span class="co"># note that this is the same as:</span></span>
<span id="cb217-5"><a href="dataframe.html#cb217-5" tabindex="-1"></a>average_grades <span class="ot">=</span> <span class="fu">c</span>(<span class="fl">27.5</span>, <span class="fl">23.6</span>, <span class="fl">28.3</span>, <span class="fl">29.2</span>, <span class="fl">24.8</span>)</span>
<span id="cb217-6"><a href="dataframe.html#cb217-6" tabindex="-1"></a>data_short<span class="sc">$</span>Average <span class="ot">=</span> average_grades</span>
<span id="cb217-7"><a href="dataframe.html#cb217-7" tabindex="-1"></a></span>
<span id="cb217-8"><a href="dataframe.html#cb217-8" tabindex="-1"></a>data_short</span>
<span id="cb217-9"><a href="dataframe.html#cb217-9" tabindex="-1"></a><span class="do">##   Id   Name Gender Age     Faculty Average</span></span>
<span id="cb217-10"><a href="dataframe.html#cb217-10" tabindex="-1"></a><span class="do">## 1  1  Alice      F  22  Psychology    27.5</span></span>
<span id="cb217-11"><a href="dataframe.html#cb217-11" tabindex="-1"></a><span class="do">## 2  2  Bruno      M  25 Engineering    23.6</span></span>
<span id="cb217-12"><a href="dataframe.html#cb217-12" tabindex="-1"></a><span class="do">## 3  3  Carla      F  23    Medicine    28.3</span></span>
<span id="cb217-13"><a href="dataframe.html#cb217-13" tabindex="-1"></a><span class="do">## 4  4 Davide      M  22        Arts    29.2</span></span>
<span id="cb217-14"><a href="dataframe.html#cb217-14" tabindex="-1"></a><span class="do">## 5  5  Elisa      F  24  Psychology    24.8</span></span></code></pre></div>
</div>
<div id="cbind" class="section level4 unnumbered hasAnchor">
<h4><code>cbind()</code><a href="dataframe.html#cbind" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>With the <code>cbind()</code> function, we can add one or more variables to our dataframe. Note that, unlike using the <code>$</code> operator, the result is not automatically saved; it must be assigned to a new object <code>dataframe = cbind(dataframe, new_var)</code>. In this case, the column name will be new_var. If we want to rename the column, we can use the syntax <code>cbind(dataframe, "name" = new_var)</code> or name the object directly:</p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="dataframe.html#cb218-1" tabindex="-1"></a><span class="co"># Add the &quot;number_of_exams&quot; variable</span></span>
<span id="cb218-2"><a href="dataframe.html#cb218-2" tabindex="-1"></a>number_of_exams <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">12</span>, <span class="dv">14</span>, <span class="dv">13</span>, <span class="dv">10</span>, <span class="dv">8</span>)</span>
<span id="cb218-3"><a href="dataframe.html#cb218-3" tabindex="-1"></a></span>
<span id="cb218-4"><a href="dataframe.html#cb218-4" tabindex="-1"></a><span class="fu">cbind</span>(data_short, number_of_exams) <span class="co"># without specifying the name</span></span>
<span id="cb218-5"><a href="dataframe.html#cb218-5" tabindex="-1"></a><span class="do">##   Id   Name Gender Age     Faculty Average number_of_exams</span></span>
<span id="cb218-6"><a href="dataframe.html#cb218-6" tabindex="-1"></a><span class="do">## 1  1  Alice      F  22  Psychology    27.5              12</span></span>
<span id="cb218-7"><a href="dataframe.html#cb218-7" tabindex="-1"></a><span class="do">## 2  2  Bruno      M  25 Engineering    23.6              14</span></span>
<span id="cb218-8"><a href="dataframe.html#cb218-8" tabindex="-1"></a><span class="do">## 3  3  Carla      F  23    Medicine    28.3              13</span></span>
<span id="cb218-9"><a href="dataframe.html#cb218-9" tabindex="-1"></a><span class="do">## 4  4 Davide      M  22        Arts    29.2              10</span></span>
<span id="cb218-10"><a href="dataframe.html#cb218-10" tabindex="-1"></a><span class="do">## 5  5  Elisa      F  24  Psychology    24.8               8</span></span>
<span id="cb218-11"><a href="dataframe.html#cb218-11" tabindex="-1"></a></span>
<span id="cb218-12"><a href="dataframe.html#cb218-12" tabindex="-1"></a><span class="fu">cbind</span>(data_short, <span class="st">&quot;N_exams&quot;</span> <span class="ot">=</span> number_of_exams) <span class="co"># specifying the name</span></span>
<span id="cb218-13"><a href="dataframe.html#cb218-13" tabindex="-1"></a><span class="do">##   Id   Name Gender Age     Faculty Average N_exams</span></span>
<span id="cb218-14"><a href="dataframe.html#cb218-14" tabindex="-1"></a><span class="do">## 1  1  Alice      F  22  Psychology    27.5      12</span></span>
<span id="cb218-15"><a href="dataframe.html#cb218-15" tabindex="-1"></a><span class="do">## 2  2  Bruno      M  25 Engineering    23.6      14</span></span>
<span id="cb218-16"><a href="dataframe.html#cb218-16" tabindex="-1"></a><span class="do">## 3  3  Carla      F  23    Medicine    28.3      13</span></span>
<span id="cb218-17"><a href="dataframe.html#cb218-17" tabindex="-1"></a><span class="do">## 4  4 Davide      M  22        Arts    29.2      10</span></span>
<span id="cb218-18"><a href="dataframe.html#cb218-18" tabindex="-1"></a><span class="do">## 5  5  Elisa      F  24  Psychology    24.8       8</span></span></code></pre></div>
<p>Again, the new variable must have the same number of values as there are rows in the dataframe.</p>
</div>
<div id="rbind" class="section level4 unnumbered hasAnchor">
<h4><code>rbind()</code><a href="dataframe.html#rbind" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Adding rows to a dataframe is slightly more complex. You may need to do this for different reasons. For example, you may have collected experimental data from different participants in different <code>.csv</code> files, and now you have to import and combine them in a single dataframe including all data from all participants. Unlike matrices, which by default do not have column names and contain only numbers or strings, to merge two dataframes by row, they must have the same structure, meaning:</p>
<ul>
<li>The same number of columns (as with matrices)</li>
<li>The same column names</li>
</ul>
<p>In the following example, we simply add one single row to an existing dataframe:</p>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="dataframe.html#cb219-1" tabindex="-1"></a>data_short</span>
<span id="cb219-2"><a href="dataframe.html#cb219-2" tabindex="-1"></a><span class="do">##   Id   Name Gender Age     Faculty Average</span></span>
<span id="cb219-3"><a href="dataframe.html#cb219-3" tabindex="-1"></a><span class="do">## 1  1  Alice      F  22  Psychology    27.5</span></span>
<span id="cb219-4"><a href="dataframe.html#cb219-4" tabindex="-1"></a><span class="do">## 2  2  Bruno      M  25 Engineering    23.6</span></span>
<span id="cb219-5"><a href="dataframe.html#cb219-5" tabindex="-1"></a><span class="do">## 3  3  Carla      F  23    Medicine    28.3</span></span>
<span id="cb219-6"><a href="dataframe.html#cb219-6" tabindex="-1"></a><span class="do">## 4  4 Davide      M  22        Arts    29.2</span></span>
<span id="cb219-7"><a href="dataframe.html#cb219-7" tabindex="-1"></a><span class="do">## 5  5  Elisa      F  24  Psychology    24.8</span></span>
<span id="cb219-8"><a href="dataframe.html#cb219-8" tabindex="-1"></a></span>
<span id="cb219-9"><a href="dataframe.html#cb219-9" tabindex="-1"></a><span class="co"># Nuovo dataset con le stesse colonne ma diverso nome</span></span>
<span id="cb219-10"><a href="dataframe.html#cb219-10" tabindex="-1"></a>new_row <span class="ot">=</span> <span class="fu">data.frame</span>(</span>
<span id="cb219-11"><a href="dataframe.html#cb219-11" tabindex="-1"></a>  <span class="at">Id =</span> <span class="dv">6</span>,</span>
<span id="cb219-12"><a href="dataframe.html#cb219-12" tabindex="-1"></a>  <span class="at">Name =</span> <span class="st">&quot;Marta&quot;</span>,</span>
<span id="cb219-13"><a href="dataframe.html#cb219-13" tabindex="-1"></a>  <span class="at">Sex =</span> <span class="st">&quot;F&quot;</span>,      <span class="co"># note &quot;Sex&quot; instead of &quot;Gender&quot;</span></span>
<span id="cb219-14"><a href="dataframe.html#cb219-14" tabindex="-1"></a>  <span class="at">Age =</span> <span class="dv">44</span>,</span>
<span id="cb219-15"><a href="dataframe.html#cb219-15" tabindex="-1"></a>  <span class="at">Faculty =</span> <span class="st">&quot;Philosophy&quot;</span>,</span>
<span id="cb219-16"><a href="dataframe.html#cb219-16" tabindex="-1"></a>  <span class="at">Average =</span> <span class="fl">28.7</span></span>
<span id="cb219-17"><a href="dataframe.html#cb219-17" tabindex="-1"></a>)</span>
<span id="cb219-18"><a href="dataframe.html#cb219-18" tabindex="-1"></a></span>
<span id="cb219-19"><a href="dataframe.html#cb219-19" tabindex="-1"></a>new_row</span>
<span id="cb219-20"><a href="dataframe.html#cb219-20" tabindex="-1"></a><span class="do">##   Id  Name Sex Age    Faculty Average</span></span>
<span id="cb219-21"><a href="dataframe.html#cb219-21" tabindex="-1"></a><span class="do">## 1  6 Marta   F  44 Philosophy    28.7</span></span>
<span id="cb219-22"><a href="dataframe.html#cb219-22" tabindex="-1"></a></span>
<span id="cb219-23"><a href="dataframe.html#cb219-23" tabindex="-1"></a><span class="fu">rbind</span>(data_short, new_row) <span class="co"># Errore</span></span>
<span id="cb219-24"><a href="dataframe.html#cb219-24" tabindex="-1"></a><span class="do">## Error in match.names(clabs, names(xi)): names do not match previous names</span></span>
<span id="cb219-25"><a href="dataframe.html#cb219-25" tabindex="-1"></a></span>
<span id="cb219-26"><a href="dataframe.html#cb219-26" tabindex="-1"></a><span class="co"># Nuovo dataset con le stesse colonne con il nome corretto</span></span>
<span id="cb219-27"><a href="dataframe.html#cb219-27" tabindex="-1"></a>new_row <span class="ot">=</span> <span class="fu">data.frame</span>(</span>
<span id="cb219-28"><a href="dataframe.html#cb219-28" tabindex="-1"></a>  <span class="at">Id =</span> <span class="dv">6</span>,</span>
<span id="cb219-29"><a href="dataframe.html#cb219-29" tabindex="-1"></a>  <span class="at">Name =</span> <span class="st">&quot;Marta&quot;</span>,</span>
<span id="cb219-30"><a href="dataframe.html#cb219-30" tabindex="-1"></a>  <span class="at">Gender =</span> <span class="st">&quot;F&quot;</span>, </span>
<span id="cb219-31"><a href="dataframe.html#cb219-31" tabindex="-1"></a>  <span class="at">Age =</span> <span class="dv">44</span>,</span>
<span id="cb219-32"><a href="dataframe.html#cb219-32" tabindex="-1"></a>  <span class="at">Faculty =</span> <span class="st">&quot;Philosophy&quot;</span>,</span>
<span id="cb219-33"><a href="dataframe.html#cb219-33" tabindex="-1"></a>  <span class="at">Average =</span> <span class="fl">28.7</span></span>
<span id="cb219-34"><a href="dataframe.html#cb219-34" tabindex="-1"></a>)</span>
<span id="cb219-35"><a href="dataframe.html#cb219-35" tabindex="-1"></a></span>
<span id="cb219-36"><a href="dataframe.html#cb219-36" tabindex="-1"></a><span class="fu">rbind</span>(data_short, new_row)</span>
<span id="cb219-37"><a href="dataframe.html#cb219-37" tabindex="-1"></a><span class="do">##   Id   Name Gender Age     Faculty Average</span></span>
<span id="cb219-38"><a href="dataframe.html#cb219-38" tabindex="-1"></a><span class="do">## 1  1  Alice      F  22  Psychology    27.5</span></span>
<span id="cb219-39"><a href="dataframe.html#cb219-39" tabindex="-1"></a><span class="do">## 2  2  Bruno      M  25 Engineering    23.6</span></span>
<span id="cb219-40"><a href="dataframe.html#cb219-40" tabindex="-1"></a><span class="do">## 3  3  Carla      F  23    Medicine    28.3</span></span>
<span id="cb219-41"><a href="dataframe.html#cb219-41" tabindex="-1"></a><span class="do">## 4  4 Davide      M  22        Arts    29.2</span></span>
<span id="cb219-42"><a href="dataframe.html#cb219-42" tabindex="-1"></a><span class="do">## 5  5  Elisa      F  24  Psychology    24.8</span></span>
<span id="cb219-43"><a href="dataframe.html#cb219-43" tabindex="-1"></a><span class="do">## 6  6  Marta      F  44  Philosophy    28.7</span></span></code></pre></div>
<p>Again, you need to save the result to keep the changes (which we have not done in the above example).</p>
</div>
</div>
<div id="dataframe-information" class="section level3 hasAnchor" number="10.3.3">
<h3><span class="header-section-number">10.3.3</span> Dataframe Information<a href="dataframe.html#dataframe-information" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Finally, let’s look at some very common functions used to get summary information about the data contained in a dataframe:</p>
<ul>
<li><code>head()</code> (or <code>tail()</code>) allows us to view the first (or last) rows of our dataframe:</li>
</ul>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb220-1"><a href="dataframe.html#cb220-1" tabindex="-1"></a><span class="fu">head</span>(my_data)</span>
<span id="cb220-2"><a href="dataframe.html#cb220-2" tabindex="-1"></a><span class="do">##   Id    names gender age     faculty</span></span>
<span id="cb220-3"><a href="dataframe.html#cb220-3" tabindex="-1"></a><span class="do">## 1  1    Alice      F  22  Psychology</span></span>
<span id="cb220-4"><a href="dataframe.html#cb220-4" tabindex="-1"></a><span class="do">## 2  2    Bruno      M  25 Engineering</span></span>
<span id="cb220-5"><a href="dataframe.html#cb220-5" tabindex="-1"></a><span class="do">## 3  3    Carla      F  23    Medicine</span></span>
<span id="cb220-6"><a href="dataframe.html#cb220-6" tabindex="-1"></a><span class="do">## 4  4   Davide      M  22        Arts</span></span>
<span id="cb220-7"><a href="dataframe.html#cb220-7" tabindex="-1"></a><span class="do">## 5  5    Elisa      F  24  Psychology</span></span>
<span id="cb220-8"><a href="dataframe.html#cb220-8" tabindex="-1"></a><span class="do">## 6  6 Fabrizio      M  35        Arts</span></span>
<span id="cb220-9"><a href="dataframe.html#cb220-9" tabindex="-1"></a><span class="fu">tail</span>(my_data)</span>
<span id="cb220-10"><a href="dataframe.html#cb220-10" tabindex="-1"></a><span class="do">##    Id    names gender age     faculty</span></span>
<span id="cb220-11"><a href="dataframe.html#cb220-11" tabindex="-1"></a><span class="do">## 5   5    Elisa      F  24  Psychology</span></span>
<span id="cb220-12"><a href="dataframe.html#cb220-12" tabindex="-1"></a><span class="do">## 6   6 Fabrizio      M  35        Arts</span></span>
<span id="cb220-13"><a href="dataframe.html#cb220-13" tabindex="-1"></a><span class="do">## 7   7   Gloria      F  26 Engineering</span></span>
<span id="cb220-14"><a href="dataframe.html#cb220-14" tabindex="-1"></a><span class="do">## 8   8   Herman      M  20  Psychology</span></span>
<span id="cb220-15"><a href="dataframe.html#cb220-15" tabindex="-1"></a><span class="do">## 9   9    Irene      F  23  Statistics</span></span>
<span id="cb220-16"><a href="dataframe.html#cb220-16" tabindex="-1"></a><span class="do">## 10 10     Luca      M  22 Engineering</span></span></code></pre></div>
<ul>
<li><code>str()</code> lets us evaluate the structure of the dataset, providing useful information such as the number of observations, the number of variables, and the type of variables:</li>
</ul>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="dataframe.html#cb221-1" tabindex="-1"></a><span class="fu">str</span>(my_data)</span>
<span id="cb221-2"><a href="dataframe.html#cb221-2" tabindex="-1"></a><span class="do">## &#39;data.frame&#39;:    10 obs. of  5 variables:</span></span>
<span id="cb221-3"><a href="dataframe.html#cb221-3" tabindex="-1"></a><span class="do">##  $ Id     : int  1 2 3 4 5 6 7 8 9 10</span></span>
<span id="cb221-4"><a href="dataframe.html#cb221-4" tabindex="-1"></a><span class="do">##  $ names  : chr  &quot;Alice&quot; &quot;Bruno&quot; &quot;Carla&quot; &quot;Davide&quot; ...</span></span>
<span id="cb221-5"><a href="dataframe.html#cb221-5" tabindex="-1"></a><span class="do">##  $ gender : Factor w/ 2 levels &quot;F&quot;,&quot;M&quot;: 1 2 1 2 1 2 1 2 1 2</span></span>
<span id="cb221-6"><a href="dataframe.html#cb221-6" tabindex="-1"></a><span class="do">##  $ age    : num  22 25 23 22 24 35 26 20 23 22</span></span>
<span id="cb221-7"><a href="dataframe.html#cb221-7" tabindex="-1"></a><span class="do">##  $ faculty: Factor w/ 5 levels &quot;Arts&quot;,&quot;Engineering&quot;,..: 4 2 3 1 4 1 2 4 5 2</span></span></code></pre></div>
<ul>
<li><code>summary()</code> gives us summary information about the variables depending on their type:</li>
</ul>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb222-1"><a href="dataframe.html#cb222-1" tabindex="-1"></a><span class="fu">summary</span>(my_data)</span>
<span id="cb222-2"><a href="dataframe.html#cb222-2" tabindex="-1"></a><span class="do">##        Id           names           gender      age               faculty </span></span>
<span id="cb222-3"><a href="dataframe.html#cb222-3" tabindex="-1"></a><span class="do">##  Min.   : 1.00   Length:10          F:5    Min.   :20.00   Arts       :2  </span></span>
<span id="cb222-4"><a href="dataframe.html#cb222-4" tabindex="-1"></a><span class="do">##  1st Qu.: 3.25   Class :character   M:5    1st Qu.:22.00   Engineering:3  </span></span>
<span id="cb222-5"><a href="dataframe.html#cb222-5" tabindex="-1"></a><span class="do">##  Median : 5.50   Mode  :character          Median :23.00   Medicine   :1  </span></span>
<span id="cb222-6"><a href="dataframe.html#cb222-6" tabindex="-1"></a><span class="do">##  Mean   : 5.50                             Mean   :24.20   Psychology :3  </span></span>
<span id="cb222-7"><a href="dataframe.html#cb222-7" tabindex="-1"></a><span class="do">##  3rd Qu.: 7.75                             3rd Qu.:24.75   Statistics :1  </span></span>
<span id="cb222-8"><a href="dataframe.html#cb222-8" tabindex="-1"></a><span class="do">##  Max.   :10.00                             Max.   :35.00</span></span></code></pre></div>
</div>
<div id="exercises-11" class="section level3 unnumbered hasAnchor">
<h3>Exercises<a href="dataframe.html#exercises-11" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Referring to the <code>data_long</code> and <code>data_wide</code> dataframes (<a href="https://github.com/psicostat/Introduction2R/blob/master/exercises/chapter-10-dataframe.R">solutions</a>):</p>
<ol style="list-style-type: decimal">
<li>Add the numerical variable <code>"memory_pre"</code> to both the <code>data_wide</code> and <code>data_long</code> dataframes:</li>
</ol>
<pre><code>##       Id memory_pre
## 1 subj_1          3
## 2 subj_2          2
## 3 subj_3          1</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Add the categorical variable <code>"group"</code> to both the <code>data_wide</code> and <code>data_long</code> dataframes:</li>
</ol>
<pre><code>##       Id     group
## 1 subj_1 treatment
## 2 subj_2 treatment
## 3 subj_3   control</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>Aggiungi al DataFrame <code>data_wide</code> i dati del soggetto <code>subj_4</code> e <code>subj_5</code>.</li>
</ol>
<pre><code>##       Id age gender item_1 item_2 item_3 memory_pre     group
## 1 subj_4  25      F      1      0      2          1 treatment
## 2 subj_5  22      M      1      1      0          3   control</code></pre>
<ol start="4" style="list-style-type: decimal">
<li>In the <code>data_wide</code> dataframe, calculate the <code>"memory_post"</code> variable as the sum of the items.</li>
<li>In the <code>data_long</code> dataframe, rename the variables <code>item_1</code>, <code>item_2</code>, and <code>item_3</code> to <code>problem_1</code>, <code>problem_2</code>, and <code>problem_3</code>, respectively.</li>
</ol>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="matrix.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="list.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
